import 'dart:async';
import 'dart:collection';
import 'dart:io';

import 'package:boilermake/main.dart';
import 'package:camera/camera.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:path/path.dart' show Context, join;
import 'package:path_provider/path_provider.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:starflut/starflut.dart';

String instructions;
String filePath;

Future<void> main() async {
  // Ensure that plugin services are initialized so that `availableCameras()`
  // can be called before `runApp()`
  WidgetsFlutterBinding.ensureInitialized();

  // Obtain a list of the available cameras on the device.
  final cameras = await availableCameras();

  // Get a specific camera from the list of available cameras.
  final firstCamera = cameras.first;

  runApp(
    MaterialApp(
      theme: ThemeData.dark(),
      home: TakePictureScreen(
        // Pass the appropriate camera to the TakePictureScreen widget.
        camera: firstCamera,
      ),
    ),
  );
}

Future<CameraDescription> getCamera() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Obtain a list of the available cameras on the device.
  final cameras = await availableCameras();

  // Get a specific camera from the list of available cameras.
  final firstCamera = cameras.first;

  return firstCamera;
}

// A screen that allows users to take a picture using a given camera.
class TakePictureScreen extends StatefulWidget {
  final CameraDescription camera;

  const TakePictureScreen({
    Key key,
    @required this.camera,
  }) : super(key: key);

  @override
  TakePictureScreenState createState() => TakePictureScreenState();
}

class TakePictureScreenState extends State<TakePictureScreen> {
  CameraController _controller;
  Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.camera,
      // Define the resolution to use.
      ResolutionPreset.medium,
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Take a picture')),
      // Wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner
      // until the controller has finished initializing.
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.camera_alt),
        // Provide an onPressed callback.
        onPressed: () async {
          // Take the Picture in a try / catch block. If anything goes wrong,
          // catch the error.
          try {
            // Ensure that the camera is initialized.
            await _initializeControllerFuture;

            // Construct the path where the image should be saved using the
            // pattern package.
            final path = join(
              // Store the picture in the temp directory.
              // Find the temp directory using the `path_provider` plugin.
              (await getTemporaryDirectory()).path,
              '${DateTime.now()}.png',
            );

            // Attempt to take a picture and log where it's been saved.
            await _controller.takePicture(path);

            // If the picture was taken, display it on a new screen.
            Navigator.push(
              context,
              CupertinoPageRoute(
                builder: (context) => DisplayPictureScreen(imagePath: path),
              ),
            );
          } catch (e) {
            // If an error occurs, log the error to the console.
            print(e);
          }
        },
      ),
    );
  }
}

Future<void> testPython() async {
  StarCoreFactory starcore = await Starflut.getFactory();
  StarServiceClass Service = await starcore.initSimple("test", "123", 0, 0, []);
  await starcore.regMsgCallBackP(
      (int serviceGroupID, int uMsg, Object wParam, Object lParam) async {
    print("$serviceGroupID  $uMsg   $wParam   $lParam");
    return null;
  });
  StarSrvGroupClass SrvGroup = await Service["_ServiceGroup"];
  bool isAndroid = await Starflut.isAndroid();
  if (isAndroid == true) {
    print("HELLO1");
    await Starflut.copyFileFromAssets("test.py", "/starfiles", "/starfiles");
    await Starflut.copyFileFromAssets(
        "python3.6.zip", "fz/starfiles", null); //desRelatePath must be null
    print("HELLO2");
    await Starflut.copyFileFromAssets("zlib.cpython-36m.so", null, null);
    await Starflut.copyFileFromAssets("unicodedata.cpython-36m.so", null, null);
    await Starflut.loadLibrary("libpython3.6m.so");
  }
  String docPath = await Starflut.getDocumentPath();
  print("docPath = $docPath");

  String resPath = await Starflut.getResourcePath();
  print("resPath = $resPath");

  dynamic rr1 = await SrvGroup.initRaw("python36", Service);

  print("initRaw = $rr1");

  var Result = await SrvGroup.loadRawModule(
      "python", "", resPath + "/flutter_assets/starfiles/" + "test.py", false);
  print("loadRawModule = $Result");

  dynamic python = await Service.importRawContext("python", "", false, "");
  print("python = " + await python.getString());

  StarObjectClass retobj = await python.call("tt", ["hello ", "world"]);
  print(await retobj[0]);
  print(await retobj[1]);

  print(await python["g1"]);

  StarObjectClass yy = await python.call("yy", ["hello ", "world", 123]);
  print(await yy.call("__len__", []));

  StarObjectClass multiply =
      await Service.importRawContext("python", "Multiply", true, "");
  StarObjectClass multiply_inst = await multiply.newObject(["", "", 33, 44]);
  print(await multiply_inst.getString());

  print(await multiply_inst.call("multiply", [11, 22]));

  await SrvGroup.clearService();
  await starcore.moduleExit();
}

Future readFileAsString() async {
  instructions = await getFileData('assets/WaspBite.txt');
}

Future<String> getFileData(String path) async {
  return await rootBundle.loadString(path);
}

String test =
    "/9j/4AAQSkZJRgABAQIAdgB2AAD/2wCEAAMDAwMDAwQEBAQFBQUFBQcHBgYHBwsICQgJCAsRCwwLCwwLEQ8SDw4PEg8bFRMTFRsfGhkaHyYiIiYwLTA+PlQBAwMDAwMDBAQEBAUFBQUFBwcGBgcHCwgJCAkICxELDAsLDAsRDxIPDg8SDxsVExMVGx8aGRofJiIiJjAtMD4+VP/CABEIAaQCWAMBIgACEQEDEQH/xAAeAAACAwEBAQEBAQAAAAAAAAADBAACBQEGBwkICv/aAAgBAQAAAAD9JpOzs5WQdB8qMVBUnJQdOCWGWoUQgnIsINUErGolcIOrcze3yBmzQq7CoOUXTZqP9A687LdpWcFQY6DpUU4Gvahg04yFUCoFxnXKpnqUAsuchcwLCyalALFAqbkWWErxhfv6FVktJTnKUqANKUoOQFe1BUA7WCNIecG4TATEmMefdmowK5G/iqC7kuqlUaVzrUVqEfP0d5yd5XvBUpQI6UEOtoOthpUV6KcqhVPMa6sVGZSucPQCc2erGAY58loaqHVRV6BXgk5+lk5zlJaox0EKkoGlOVtOKCXUitWFhpBQWG9OqYy+fSj6jI8lxci6oSIZ90Oq2ulSgw0/S2cpSvb0pUQA0vUAq0qTgFaqqHzKsiVEhfNcUTJEMgWY+fHfGonqKwVslSilq9FVINAmB+l0gaTs5yglwDJ1QPRUrRcS1wXUX5ZUnnivYZc8glU8haLLD9EJFdxXr2P59MktUQgzilL/AKZSAH3vOcEIYh3EGoVw8gFAG5zOnALr5/W1ci8qmqnmYW7haOolUuVpLYJ8Ia+mqVFWxLqUn6a9itJJBBHwfIsLqq6/OcVuo4rmmZz8WqRqsrZ1VJfyqBrYqmlTSiw1Inngt0IKhJYStTfptYSs4OdEMc7BpLwQlZetFcvlkLM4Q1GiIXzHfPWJ56YTSeQOu4N2LiCNRGleBVNBhWJP1B4AE4KteVHaQCysEMALUoHOUsC4My+OqJ0MFn51ls862MtdYhdB/LzIAC6RqFQGcIecn6kVCG9VudgqSlggCEPBcS6usLLo4ohRfO6AOniTMRtmt5LPmsZhfR7pdTVvlqrmWYFQVLDrQf6rV4vyg6XoLnRQfUlFeiQsvFUx8EIObmh0sd5WiSYFsneZ835XzKzeq2vpUSQ4tlucImMQSXGNb9ae1XBzopyklRWJj54bRUQ1O5joM1ZTzeplbXFvJbvmbYOifSU8v5PD8tseorrrky2FM2s5RUYg9NUQv11pQSwzVpwY+dBe2dmJlg8sDeWqylfAHRK+l58Q8G+K0xqAyvN4HkMR309dEzGSFZadUstOLDjIlf2BWrVat5wYeAHWgU1hlCiHJWq8uDNzuXKEbnjgeOYXr6TUzvL4ON5bA3du55BrVXVYnFxCGtwvFv2DDBhtAygRrV5El4sJdeiiajK+dj7nk9y77vkfPeWBlaD2zs+RwfIIedx/Qa2sk/liOqJW5a9GksEcEP8AYzlQVuIPUx1UvKppFXADNZSTqGq/mjrelzzh87j+RXIr6L02Fh+ZzMnHST3tWMUXioAcLYgV1BUEMX7JVqvSDuLPoRAdajUg1UiCABcObSmbTWz+K44MPOTdW0K4Wd57MQQzdNzUuEZVxqDOXiQgU6Hgf2PtQAecoNatEg1CBM9MrohUTRPdJpcHMb3vg/OZ6K4sl3P7l88qulm42hux8coBcUIKivKSBi/7GXCMQ5RQTI01ejRpSmPci6OaLF9MyISXksT7RqfH/i26nETaCnn74AMgGPXeNqEtEc4hqdVUofoR0r+w1lZxaRUFShy7ATGBpNVLLTSeDT0eRTy/hMn7n80/i4H1Hacp6kNMJbKBmZ2bb1mmq0AqdOlRLxMDfRjqr+w9l4MYF4MZAoqwWWiz5XJ9fnp0zLaPlfZeO8bxRvwnw7wX0D0X0Bt262NmYuKvmzd9CFVggBhNApXEI84Ki37F1lBjAnUkGurVRNLBth+W9le+ePC2fkn2L5QvvY+aj81wgfRvTj9Z82MPDy/IrbhdW+ZtKvZIO8qqClRXr0HFv2U5elRrKjnFqrjgPgHp1Nz5vu+G+nee9b8O+nfPfW+RzN/5B9B8H9D/AJo9b6jWZ9l8iJofLdxAmB6rF97iXOValKBCLog0rUdAfs1S/QxQYOCGkqXuT8K3vY5WXu/EPoinqfiH1v5L9q+dINfGvZeR1vkmv6I3oweK20cLIcdzX9RHyfrGzIJSi86Ma46jH2n7Nh7cNKhWEuAaHIsv5r5D9H8x7j4n9N857D459l+Efcfl2Vr/AB/6eXM+EafrmsMGH7HNXycfaz/QaqPl6+vxeBCANODpRekrS/7RL07FpRNUQhBAuD4Q0H3GB6v4x9I+R6/n/sngMj6D/Pvv8TuL7H4X6UOah61Dzfv/ACOFk/R/IPA9bk6nlfTef7UK9FxdoqC3R8/asavCBEoKuePhEUw0yS1UxnsICGhmXIkjzURyvl3nDP7BMquvheNcHm7VwibR3MvHnbpqhlhLq0rOftXRWnRLCB1ZRQF2M1dBcecJdBBhRWmnm5xJ3wnjvK+ne40gqPz+Q0wqQZBktM/nakXSHaRAAaE7+1FAD4IFBAVTCIkz0s9VS2WJnGViJb9y1/NtefwvO7u9lWyVVc0IblqpNLtYAIg9Xz7UoVNOtb3/AGqBUFgLWEguvRW9M5Oos0vnu8zxKPeVZDMbyr1MTzu9t187nIZME8ZQKy78jglgiuDPGBfgwVvev7XK2FFk5E1FbDrloDBfJbzQ48zrCxkmq5HmLzGQJ6dJPyueqyLUEBEXBietwS9bKKVEMdB9tYf7VClBqrBFUIlli5aYRAXWW8zLcLkLYbK2V45/OwWCemX85nDFzSXSXGqSWHztwD6BQNSiqPl4L9oujBRdZZIogri6iqDOvnqJ5gjgBTJVy8wGCjmhmi675bO4breh5tFcLQbd6KnRjXEDlxyo69p+0vAqUCqJekUomAeeDKlaZ6uHpZZlOeVrjTzaSWH7NPQZysRtR+L5qNAdlT2oAFwgGvToOStai/a6iwADzxcHBKWzgVzFQczK56NlV8/mPRfLyUALsHdXUrl2UvxNNPtqqGg+claiWFQFLSUB+1EoAIVFRrg5xCZ1kka5/EAxAXcsayOTZTzNoi27mh7mZryj+SgLnOIt9UNRaDuCgIIfaXD+0EqESAwo3CuAA0lp3NQa8+fIZABTM8zpKF5fyxUrqDPkoLTsB50ba7avaWnABW5LDEOgujn7OV7QSglUgGWUVqvnDLljAmobIUDa2PnQ6La2Re2d3GzKKqEYUVy1elE4MNg1HUNZylAVFzv7L0tBD4qsmAaQ0V0r9WRTVUzmMqo18hYbqg7JjRArfyhLZ6u2PPzs7ktbgrrLy8ga2oEI5X9mREoG/ADTyaLCTDfOHkVHkOoqqrJ2TVQ5VAeimnbGYy11KqEGBIAlTSAqmG073g5BipafsovcYLgU5EgBUWRAuuktWqKNEqJormBm0RPl6eQRBNYochJtY+TwCfJVqiFb8GSCEPlOVn7MDAIPaLAgRJBWUQCrxdDOWWIjMghCY+cqVjLTLmkREBFSnc9PjYczkETg6DucY+BGGgh1/Z6wUQ85FlOrUTBXJTsiECWXTPNTqSqqSjOeEq2WcAM6ywVhJiydDqgOjg16jKQMqKo6UGD9m71WWXEaiIQA5xFTPVmWGquaXJey+ZuaWZ1MzkXsGZFZVbNKJFIwxTtALS3K0gk72FWg/wBl6WVWD2yw08gqw+rLIcWzUuBzVhXylz56dRgX5jtaCC2dlsJ1ApE+FHwYAUGbg6dqqLkqMX7L16JNRg6gVczmZD0yq5nUsuqRFa49xZgEwotzPzTvpec1POQDgUpnynQLkqtS3Q0lF6ScGP8AZLl6pLE6NKqncpW6ufQOKqda1UKjyVIivUWOKguKlQokBZI/OJVWpZSnQgYgRjotXnO8p+yHR9WVoSoM5Ui+eXudkJGUBzP6qovMcBaoIcVWAlRWzGVZJWgSI9GkOgh95bnOrjEtXlZ3/RPJJJJJJJJJJOJGhvLvF8t7RTD9FfI9Hlmmgl58dyqQZGNbWkkkkkkkkkkkkkkkkkkkkknybF8L6v3HhdhLa8p6RXO9f5r1yOLz7hn/ABj09PKaaqbo/Y/SZJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJP//EABoBAAMBAQEBAAAAAAAAAAAAAAABAgMEBQb/2gAIAQIQAAAA+aSJlIqZSikmIyuLl5OU7mrfoIRMgiKzTUgzJXUkDkbG/QJASeapRKqQV4FwqTEwB+iQwlJSKXLU3nUS895QlYrmvRmAQQ4Ty0jTHQnMjXDS0rmpYtO6EqkJZJnFzWdTlVQ6ZKpooffMMQ3lUJOZnbJQ9+OOsRI02P0TGlIGOmadSBjkduHNPoIyAbWk9wokVQQlpGelnEurbgiu5RmFXNUdcwgyaJaYVWJIsyr0gQ2qZ0yhaYEVmZX0rz8/QyzjWHdbTKpqm3ZMNzm70wnPvy5Yy9NlcOevT0csqppsWgokb00rC8tsstb6K5s1l2Tc88O2NkCvOUbbzjo5nn7AeJz9nRAuWbpNsyipcskc43Oj24N+hrLZiJNFaarlEJNwKLhkZvfq51W6ViLaoRy1EuLmLDO1MzenRg9bTGDpthxJSk0Rcl1lAdVY67JNttlMH5wZlCIJukwd2wZdDLTYPynMzbFUqi89Nc6q5oejE23QV4dhDbTihuNHRbooLpUUUUeFQJNqWBVLSgdPQHVjbHT8Cgzp1laKsmrCy7Za0KGOqPnAtQUOhDpVdWrdt3TG27D5osiaGjSoZVFunpZVU7adVT+hAAAAAAAAAAAAAAAAAAAAAAAAA//EABoBAAMBAQEBAAAAAAAAAAAAAAECAwAEBQb/2gAIAQMQAAAA9/DM1aVszu7qKkA2GV0chgjGY+VwZq0vWpoKMod1DVaaur4HMuK/Is+avRR7MrMzyZ2VOh5vpjMxUbD5J6hq9D0o+ODhqwsj2ZuTbVrEGeHytqlrsenOARWfQik7pHRDnY5lMwB81drGha2xD0V3ZC21KpAVwUBVn4FLuaZ9YNnD0eL6m5u/t5ILTCbKqD56vSr1JaqO+SrqnRc8FOzu4JK7JPFF3gUo9KOlQzMGqsD6FOfi7+mvHB8dKZB3z9bNZqZlohc5J2pUCttuUMNLKu3jWo1p1Z0o1Rzjvn4/0e0LHHjBeaBE286j2KvQpDqo/n07rdDcvFD07nh4OymQqqheIUsSywAvO8m6Ut1eXnp28AiexxIEKOBmNXfQkbSZ26uK/p8Ut2cfNl3pbTBUL5/QKmgJoTaVJnl9WvCm6JJN1ppFBgnNbOaslHZkbY9O3DemgBM4IQgUTLVzmlUJZWrrqnH00jJl2TIJqJHNSpWlGOfJuijPyc/UkFoECBdILMWZrFg7NjlocXlB6IhUKECJhJO0NV9TOjEbWlOiYVWbzQKmQIon6SDVsz4NgdSYQ7AyfSmuRQqT3pnHalHI2d4nSYFHkAs5hQgQS9jVXZjbNspcKrSAwVDBQJqAh9fUlqsc5JLLlQwJyackyrpzXD2w65tQVaeOYKVChcipJRMzCKPjNttttttttttttttttttttttttttttttttttttt//xAAmEAACAgIDAQEBAAMAAwEAAAABAgADERIEBRATIAYUFTAWQFBg/9oACAEBAAECAf8Amf1mH8ZPuSWYHwknYsH+kYRoT9XEQki1yXayywRmtiE2Xkcmyb2RGI1JQbuwc+M3/M/jOfznMyTCTB4Y3hEJIVmbLCOuALLRbqxF2zEx5l5kFg1usQM2HhhjxZtk/wDYw/jPp/BmS2c5yxyzZJE2J2N99SOzWQvY48VGe6UhltiQo676rYzbZdzaG3aAs25t/wCmSfD+8Q+H0kNMv5ZFjHOzRollwUm+wV2obHWOFNRWyxNmfJm7TfLH6kamFsuc/rP6P4P4zn1jCdssQ5bLNlhZPqXVhbgtZBU6o5gZLzbu5qtsiFooKZsgRiAylAScmCMMf9DD5kQw+nwEncnZiFIaAZYA2BWtgVTs5qZixeGNDYj2Nx3NTgxeRYwZoWsH2e0uLdsmFj4Ttkn0/wDA+HwQw+k52ySWzNtmghm2lhsZYZYjRaLWS6wJGeC17Ws3rZpbKoFexW3tZixRTMzZm2hjRfyf3k/kk+ZaZ8bzAmMFsYMZj5ULDk2cdnZ59rBuSa2LOlhtF8Y12Ysba3xwtkJ2aDwEkzPph/RMzk+GGCZMMznJ9LLHdjWzOwtZbHDGpmssUS6vjF1S2xnfZBZKjNWasW1pa8R7I0ARd852aLMsciZ8P4PmT+mhmST40ExCrSw12WeCO21kDGzbBgtd/stl8MBNbFnNjul+UbIOhOGYhiGYRvck5MBJ8b/q0IhhhhBAhhaOC24GzQu8aVnkpxntiUs7pRUL7Hau2cguS2SBaTQXLWWMhabtC31DGMQ2ckzJPh9MP4P5MPp8yfCXIawaJMuFd6lZkQqzNbEssP0dbWRmoWXI8ewOLmO1T2XsdrLPszi/YTJcknfbYnYMfT4fyfD6Zq3hMJ3YsUe0hnJhYS0qXuLVJatltUZWvss5F0VqE1susLEWO9QYLM/RyThyQJksT9GfYPtsWL+t5mH0+Z/Fsz4Awy00YqdrWM3tYkJYoa08onk5u8tv5zVce9mvte08izfj3WPTaHDuDZDYzg7b7M8Y5zsTkn0w+n8ZzkxSxaN4sJaNNw7GYqstdmRgKWsVRZVZMI2xa6pEqm3LtvBnJLSqMK0LhvvbBY5zljlvM5MzmMS0JmT6fDMmEhidmfYmE7M7NYK2seubO+4qNnyllVgU3R67DVylvTmcSywi+8te9l5LItUIWvJcnxpkHwgjJJOdixJh/GDMwwmEjww+FcMY0MY7mVh3viXNfatSLw0r5jVJdbY11ptfk8VKn5PJxZLw8tErZWyltkKwSzwwHJMMaZPmSST6fTMGFoYSCYY0J2y0JxrYFqdSwGt1FamMnGd2dLFuNivLZdOIzB2ex7LjaXGoep1fGSxmzNsWzkHOxOZknw+GH3IhLRY0aKxbdifCrmVtYzLvu8C2TV0NNPKDCo3m62lX+gZmaJZVdyDm14zWwSsggkzJ8aHwEEkkkkEw+H0/nJJgBjQetA0+jkzQqLDGgdyjXXfUVWl77kr4XM4/LtIawwUWWJzL0LgWTEu8RkOYI4AJJMWHwkkwTU+keEw+nzKkxxkzJmuGFkB+ha8qXcKosNpet5by2v6NuXzey7H/AD17Fr1vF1bVCy20u/0dgbGLK1TbbiE5eNAZsYfM+GDw+GHw+5MMVoY0BYPGdLiTHgW6PagcGGUl5bZdfaUv4lHJ7PvTxefV2CdjbyOMbKqrrhY9jEO29lhYShTQDk+4AIaBjD4vh8P4Ph8J2/DFvNyWOme5u6bkAu0epb7JxDd3PMu5vP4/Nqc8RLO2TveN0StOFTxuI/HxzeV9Xo2tf67MVqqrvbruRkMZuzBtti227NttttsWJmfD434PjHJGGlznua+x75en5X+3rbktXelb857QW7jvud1dyGWdrZH43H6Y38Wi/knnX0dvzE5NpuBPKqSHipyV4/Lbqmp45e+phjEMMPh8znYnYk/ow+nzLTLBJzL/APQp0ffvwOut6XicnvB0i0V9kOfxqweh7Hh8Xgddx+U6dPZV9OfyuJ0fbTg9Td1HFXsKE6/aipes5VvENdf+nVO3HS1c7lcPjO3pmT5g+HzOYYfxmMD6THm/meXQnf8AE7L+gn86zHmzuT0ppnMbHGnIf+ibqHE4XIPY9ryeLOsnJ5nLr6vtm7Xknu7qrbx1K2D/ABW4/SCf5XLlN/VUW25cNAS2c+EnzYzOTD+DMwxoSSxMMBLtLK7On5NHdN0BU8yd4OiKnlhxTOZO9HV2l+AeT1p4DTguaOvQt2XF4bdtOJPo/NfhduONOlnxNXY09fw3WyFtj4SZnbbbJbbMzkw+ZhmTG8JPmIRYy8tu64fC7l+iFc7GcxTH7zj0chu44fA5fZ8G1Ottv4I7aijktwZjs3/2uxqu4tE5Upfm8tKK25PFPZ8Th9nb1UavicrlVCGGGHxvTD5nMzDCcwzJbYxopL5YudrW+Zd4LHb7XkXR73s+r2ENYTQeQ3M5V97diZwuaX+7rx4/O5HJsn+fZz1WrlDnX8unkWc5X/zuRy8zJhh/BjQ+Z9JbzJOSPGmbCriasCXjn7bugNjI9x+u11tT62Fwzfe4Xlkri8YJYmLrnudndQK9WAQzGuCXghgmSSfSGmTBM+En0/gsYZg+CWTZmEshSMytaVfHwNsIecqwcj6WNYHiqS4a3YkFoVWM6O53+iwspxjB9aHzO7OSSTM5Ph9aAxoZnJjBWayyxvC4ssjT5VtdXkH6tEcWcmcg3jive7oBxWFd1rAS+xbGYNoqMGhmiMxU5J2JHjEwliTsTn8H8t5liY/gOXDRlyDZGCuwe4taa4bFa8pBYh5ZttLWNYVWq6h2l5d3aCsKrQg+BmOwOxaE5jEmH3GMYwRn0wwzJYF/DGCx4Sw2doA7WGLELzU1WvU7S+97BZuxU1Si3kHe6aNK49WCd2bcLCohmYwAMPmfMYxgeH0zJJhjTOSds5zZDMltXZmuKh1CJTa5Q32DGOVDFsZTbqjfCyu1HKVt5WWW1iZjPmMMAc5MJMMHmfczOISYSZkkiMGGHG0eGWSu22FmYwnA5OUtuDGw7CWC2vysGLDY5MSMiAl3sWPasMAyGzkw+GEQweZDZ8znJ8PhjTOSdti2zKC4YiN46WtWHgayss7lmTFo3t44semukGEbKfm6htwbBHhQDYnOYTkkMTDCPDMemGZzD4YYfDM+ZY7/AEKkMDDY0aZeFAmprtDtqJyVs4i12V0QV4E+WxdioKq9p+mTMaGIDDBD7mEmGYP4yfBGmWhOTCc4MLHwhoru7Oosq1M+hGGaxSGsw7JUH0tQJpqy1zLxlaLHsEtRwkJ33YmZAhMMMyDD+c5hOcwwjBjwePCsYtGdWsBhUMWDubYpaJbZHn2Wx41ObK1ruSuxiWtYnbbYEnZg0Yqc7RpnJJbMP5MP5JHmfCCNWGxhZiTmxRA1h2ctGOWRrdij2F+QAyuXe1nYUvZYjMnJQIa2UwFFshV40AizbJmS2wfaGZzmH8mCAtM5zmWeZYQ+5tQGyCywqWiiziMFdkNjj5oQmxtUYloFhstMeGF1syzMdc7ZBPhLN7nOJnJ/J8yTMksQ7ExlBeHwsx3si2PYHLPawZ3DgRqzNHosIDkWKAkMIDaWOXJWbEtBGEzncAhkxMQAzBmfc5hh8MzlofdnmxjISQSQI6LVaFjNYtdlrBPo7OGscVRrbGVfvAxNlZLeBcWuGyAY3mpmS0MyPMw+H0+ZzCDMzMYZJhmJmzxlhDO0tSpXZLvsbNr0D2XfNZpdDOQWonxNjWNGVK7ICUYMK7DCIZiNMzAmc5JLZMxD4fMsTDMwwzJfcOxYxwIyNGhLE+LNo6szFS1hs2sisxawitrarqUBsFjzEy8MDMZjwwzGMHwgwzOSc5Mz4YTnGMmNCTNjNWhhEZLQtrMrs2HQOY1jGwlh5apoeyyvjli8e2xQ2zMheBipmvmSTD5nOT6YTn0/kxhmAvMumChER3Z10aEmOmr1ojlnsCqxK/J7RHGmGs+z1I9ju+b4jCCGGpplpsC0ExCPDM5hOc+ZPghgLQwwTJhm58sm2tib7u7k2qbGW5nKa5smcfT5FXttaFwv0byws8IKnzYhoYRGbOcsYIT7kmZzkmD3LEmbR5nOzEwQl482LawuXYFoVItqQtGulhCFjSGJrDNgKSI7bQR2PhjHJhM2z7jBh/8AdflHtLOwfsK7+R/Q8Tu+x7j/AMyPZv3fK/qm7fkdpwe75HIPdX9rX207HnP/AEVXf9d/Q9d3/D/oqf6If1HI/oL+96vtP/mf1/T9V/MUfzHefzHQ0UdVz/5zk9b86v54dH/h9l1HG4nVdH3PG5VPVfzvD/nuTxO1fjddw+O3811/851PA4nH5X87xumo6P8AlOo//Q//xABJEAABAwIDBgMDCQQHCAIDAAABAAIRAyEEEjEFEBMiQVEyYXEUIEIjMEBScoGRobEVc8HRBiRDUFNi4SUzNIKSssLwYGNkhPH/2gAIAQEAAz8B/uI+7mRasyydU0iyvlKIN7LPYn0Kg5Sg30QktJ9Cho9ObyuGbsVGo9Cg8cSmfVNdEmD1TqbiR9669+qphwtqPzTg7K91u6I6QswDXa6LMLI2a42TijmAPfVdUDeVFkLrooUm+4KB/cR3QmoIaoFFhWYSFm8SDbdF2TiCD0XZEX6p1bobapiYOV8eRTS0C0sTHm/4KnQdmFwdQmPAvGbwp1LlN2qk3W7T+SuOyD2nyQZ4+uhTXP8AvRaLrOE4GDohKdosl0H6IsRWZCUP7ksoUq6k7shWYLLoua4hPIkaLMI6hZTPZNfzNspsfEjTcHCxXEZxGfeOybVZEXb+aDBxG2ITK12iO6DqcDXqqgIaYLJ/DzXDs/m7KRYarNLX9NFB7IVGa6aqpTEa9lIn81wzB0KBUFNixUrLZSENFCsj/cp3mbqNE1wRaY6Ii8LOntbB0R8bShUGb8VklsWR6ymvp5H9BY906i7MDA6juE1zg+mdfyRc0Ztei4ZkWcn1JFs0INzNJuhOR33LLcKCI17plQSNQuaUHEHUIskdE31WW3RdkQZBugVm1WXceqgKVCn6ZHvjcSsiBsVwzIuFxNAhTs5SJaos6yNN0O8JTGPaQbOUVCH6d04jhN1+EoGz/F3Qc2QfIoU3GRynX+aDqbY0PVCMvX9UZzA5TNlSqNDtHNPMgTe3khBbU1GiD/IIB2XoVBvqgwkJzk6U0BOGm7qp13ZT5KV33x9LG+AjO8oSiQiHIIOTIh0SspshV0K4RyH8U4ktcE1vJr2KJtKzMvzEf+2Tg0OGg0Ta44kQ3+KyCWkAkoPMt/AqzqTtT4VmMTEIEybu7Lhcw1VOs4ZR0uFxF3R1Tqg0RHmgSjKCzKEECh7kK30yd9vdlygIgomHJjhyqHSg9ssCLzIOidwrgI1AGO5SOvdTaIT3uIHK+LH6ydTdMSRqskE3BvB0VP5QaBwlv2lwWZX2M6I1Rma05gnvNte4T3sJeIJ/NQdIK4lyhR5okO1XNLVeIUnmQykdl3KymyzqQouFKj3yP7gvuKyp0JxbKzo0zfRRdoRqi4Nk+lJAt1Tqslmsrg1JqCe6HN0PRPruDHDm0kfEqhbpBa5CqRDSat58/NfCbzoPNOJd0jomBoLhnDxZ3VGk7NNjqPJBjumQ3TKjIZ0TXSJlya06popozDjA6IG34pseaqB9la6PVQnZlCymVKlHcd0fST70qENwhNKLDqi60J7HSnFnLdSD9YIsh34pjhxOh6LgjPlkHVcgeHZg7QHVOJ4L/AfxsmfC7TRNruy1LEj8SOqLX2t5oVWl087fF/MLkDPiMX/muHmYbz4f9FmzZrFNpiH3B/JRITQM/WUxzRlUOugnaFEXTXDzTpQcLKR5oLLZArLuOu7vun6SN43dk7dKyFB7VUJgKBB1Q+9SBm0VFvKHaohod1my4jeJ17IMzNdYH9VDQJERqhSf5fooqOz+XOOnmhVktHMPH2lazqqdek4OniM89QiR9W34p7WjSeo/iqhZqi+58UrMIWSGnwrOJ0CDTfQqWmE5+uq/FTqgLhB0oDRXkKVK5ZCkLKh7hlSo+jT7kLMoQGiBG4dVI5UA66NQZgm6zEKpmv4U5umqqGnFraqpTMzNM6kLM/Ke0qYp6np/JZppgc8XT3VX0Hu1FgdJHRPoES3l0LVTe6emW1uqqOOY2I0H81x8tRupMFqg5uqc64s1NaQW/espsEyo5ZLO+5Zx5LlhQEVKdoUdUTO4tKlQdxRCPuR9ICg7rIhZhugwgxTdPY6CmPQbNO5TWc+qL6JaNCmPAY+xDrFVKFUk6O18wqtJmjSx10Xk0ub/ACxr6Jpp5MpEaWRqFgIPEYDBGpPRVuZzzkeLjzTXMp5fEGi/r3TaTxnbmHWenmEc5h8t1BVZlUOpjREDN3Tr3QMBOczXRZXKSsvohorrOuhQ6KUdQuZAhXUKPft9DjfbcZ3WU7inZkYhEthGFnFhdZ7EwUaZ9EXcx0PRcoadDcK8iU6tyOHyn4J+SozNdon/AJVTZQbfmgkjqCuJrYtjM3qfNCGuaMrgZXGpAiw0+9MZUNLQO8JPeEyXcUwdJTyG03gimZLAsmd3TQIhhZ52Wb7+i4ZWVwJPqgTZFreY6oEapzXeSBUCFZO03BXldUdVI+ZP0GAp3X3hqDkFlKEIFya3VZxypzbnVCU6nLgqufONFLNLHqvZ3eXZMqMa4O08I7lCu0Ps2VSNKCQKrNSqzXNMT59wqdQiqx8v19Cn13Oc2zwDJXtFPiaubZw7Kox5kSHaoV3tNLTKD6IVWNLjzzF09gawkkjRZ6EOsQUOiOaWo5fNVJWjXKWwFeCm3V1bcCJUWKldFl3AIqfej6FZT7hUhRooQcFMhZShVajTdBQmUzmylGow5tAgKbzKrOlg06Jr/tz1VCk7gObObSNQV7PW5ycsyQFRzsc4R3Hkeqp0nOFW7TIa5NFThuMNede3ZVKDXipYE5c32eiLCHxE/D5LPwy/Sp4T5JraLuH8JuPrIVJEQD+UKHNYbiUGVcw+9B92q6hyOqsHIlsypddNHL1QAUhDdPuGd8e9P0GPdsgrqyMJw1V02oEaUppZPVcRFhcfhRY/L8JRpt4h5myhkFRvw3CFeqHB9u/ZQILYOudDF0KlQHnaQCmOc3NYdx080eH4jDDc+R0KdzAGfNOeznY6pUEx5BPyuGSQ49k9gFPpNp+GVTw1Vr6nNYoM5xd03VPO54vZB7jK4fKtd19UMohOIg9EWIO9YUFAFSre/f3Ov0GfduoU7xvCzo0ryudDxArmVAsDRcp73RMQqoaxr6gAcLJoqhpc52bRUMFiHNLhBGqZWAEAj4neifnqhrr5czQBZ2XonGWw2T20A7ote3mDw2bfCUHAFosixzXM5HNCFVh5cozSR5+SFWjXJAGUABE0ganhFh5IFvkskuHXVBxXZcvmipWWyh0oRfVZX+SDgpWW26CrKFbfZW9yPoEHfO+Rv6ouK6FSNxpwswEprmz2TDquY5UzJlHj7qX8MHn6oMwnc908OcatgBY9lTc4VAAGtMFUw97cvLmhpnuntd8iXAs1M2amiiMt2OiT1kaynOEsaSOqfSHQhwGl00ta63MJjsnU6uZlx28uyp1WcvR0uBTHU3PjWxTW02kX7otJ806Y6EoNEIRZSLoNaibK3ms4UFFu6VG6Le7H0qVClWWYJrbFS5HVcpQeIKaacdU9onoqjLwnVhLRcaqtSfnAuQqlnNF9ZU0i2oNDy+qfiG1A6G3k+aqsp84PDHhjrK4+HbRZqOZ57dFLMujW3d/NClRFMjmyh4n/ADC6ZGWYJCp0g8M5swgpzHHkJY7/ANlU3in5N5lTNSGCJ6qu0OY/ma1MlzXGxUP1ss8+SBO7pu1Vk9rlIRF1IlRvla7rR7tvnY+YKsjO+XLLCJujCMQUCZWR1k14hBrMpWeQeiY2mMo5k6qwgBBjQXPlvlaCi1jCyJvHmmU+FIlsw8Hz1XtTOGwikwiA/WfSNFXw4q4ephXjMbEm/wBpV8HnIZmBIaXD8E+vmqPqNmc1lh3NaQ0y828ggyoy3xXjqq2JfkBy6n7lToua+oS5jpVLKfyTw5oInojOYa6o1BdFtOe6zOR6oEqUQVBWYFEFSFBUhED3I+Zn3p98Qr77KFKgboG6yaouobKnqrQqzXZh3QJk6pjWggc06d0XFltU1tWPhd1805usFp1T6bhTvA8JjRZ3QLE903Z+z8RUqVuQcxjoB2VGs0PsczZB/wBVRq8KlVq0Gs4gBcD+qpYXar8I580s2b/l7LM51NhEOdLSeimcocXAeMqtTa59mu/gU57SCbBcuU97LMT5BPbYo3TjSgpoVpRkqFqrpwC5gVKlW3ws28fP33So9yyupRRCsggVJsJRb0O5zSnvbCg3K5OXVOLddFUJDmlNscpc6FVD8v3hF4yuqDyACqNEZ7p785ue6NGsHG+Xp0KoVKNWpQqvdRxNKDROrXJtVz8NUqcNtEFuXSANboPxVevQzUsNRgtbJ5z3VTEYk1M5dkaGAoGmGEgD+KzjK53+qdW5i6/ZOfVE6ErhaGU/m6SjpojmhOKtJVllU7nSqlWzWuPoJVRo52Ob6iFFt11O/KdxndZSr/RJUKQgrogowqtLAsdTqOYePEtMdFXrDECpVe+GiMziUSpK5oU3BRpvupMo1XNYTCq1a7aNH5FmcX+IqSQAczTZDZ7GVOFmfVza6NhVcVgqtWq4lza1u0IVmuDW88k+gVi+ZIhVG5a7Hc4e3MG25h/Ne3VK1Rw4RMl7ZkEoeyu4cjJ0/mi6l3hxsogCBlF0KtVgeLODoXibVbBaPxCuDSsJsVUpuNP75QwAY2nSmrkDs7tBPYJ1fA4WpUcS88ST96zCVwwZWZRaVO5zk1sBPo7MzU3OYfaIlpj4VXq08VxKr3xStmJPXfbfffb6DPv3UqEZVHDtz16gYDp3P3LZoERWPmAFgK5ytrZD2eI/NOGBYP8A7x/2rD4Q1jXcRmaAIErZo/xh5wFRr89KoKjevl6hYehT4tV5aM2UQJusPiWPdRqk5ImRGq4jwB1Wz6NVzH1nWJHg7KhgKtN9aoYdOWAhTrU6h+FwJWzajwTUdrIGQqhjKlHgy6M827rBsoPZiH61M3hnosC7DVn4c53UnjNLYkOVKkxtSrWFJj7wbk/csHTqFw4z/rEAZbKlXk4R5LomHeMr2kupVDw7OnNpHZUNkP8AlKhw9OrmcC8cxDuwWx6nKPaMrdTDVROLoltgGyToIIsVs5mXPXfUe3/DFvzWzKsOD6rL3zNmPwVGqONTqtNJjZL230VPE4kOpHM0U2jSNFgTgaNOpVLHMzaNnUpj6LH0Khe1zsukXWHo2r4gNd9QDMVs2oQ0Yh8kwOTunUqz2TOUwjoVRpNDsTV4ZOjAJctlC04j1hqZXGfD1RVi5bo4fch+yf8A9n/xXJi/3S4pNw1rRLnHoFs4H/iH/wDQhRLRmnM0OuIIndO6dx94+4fmbe9G4F1+mqq43El5uXuho7dgjl58S0O7BsrEDEU5LH0s3MQeiz4Bp/8AyB/2lVMe5/OGBgkk3RDTwsQHujwluWU/B4ptQGIMPHcdkPYWZT/bf+KMYvzaxOpVmmbSpxVc/wD2v/VO2hwGCo1rqffrICdVLG/WcAFWa8sNekCO8o7P4cuDs8mR5J+JpPrB7GtDoh0/ihgqVcVajajHQ52Xsy6xONxXEdc1HeCfyTX049qpsc1pBZEwq2BxPBe4tLLtc3r6LC4ui3E1KYvTOaB1Z1VTHYo1Kkvc8wB+gTqnydXEUqJb4iQTc9Cm0uFRpuljGMc4/WK9rpmtxAyl8MiSUBPArsfa7TypuE2ecK5wa+vTcXT0J0TsDW4ZcHSAZHmn16DK3GpsDpgO8rL2DZtXK9r30yYI6F9lWxdXI27jJJJValVY91WjDXAnnTX4qq4GRnMIMNWsRIpMzD7XRV8biABzVKh6po5fa6WftePxWLwmLyNa4VWHpdf7OacuQvrNc5vYlqNT2lo60x+qYWez0D8k08zvrlNwzBiqwlx/3TD/ANxT3uLnXJ9yPmJ3T8zf3oUqQrLLUvp1VXBVyx0iDyu7juq1uLSp1PPwlYHGwyDSqHQG4P3rJgGfvx+hTT7V9hqiu37QQ9qxP71/6qMDS/eN/wC1TTxf2WKXtn6wUYqu2P7V/wCqy4ymesfwR41HIfjai6pUy2LSi+ngyDMtf+qPsNbNzfLeHpoow+LdH+8oVI7QF7PiKby3Pw3SVg21QeA85yfigH1VTaD2Vm0iwNaG69lUqbJeDbkrfoqVPaNGWzzjVVX1a0nlc68eWifUwlF93QwB8dD5qrgqRo8r25rNcFgX2q0CyfiYZj7im0mtdTdnpO8LkTi2fuWL/ZuEH7z9Uf2fifts/VH2l5iPkn7sPSDONiWsL2hwEE2Kps2din06oqNcGwQI0K/rjfsP/Rd1isuXPHn1/Ff7MuZPtP8A4qpTa9rTGcQ70VKtVeX83DbmFP6ydVrZ3ob+/uT9CjdfdIUboWZZm5KlMPb2IlbPraUXMPdp/mjhMTUpZpyO1RrbHwtR2riwn1yosOK+w1B72n/MEG47Efvn/qm+wUSP8Rv/AGq+JZN3MBH3FfLMjSVOJrR/iv8A1QfimfZA/JOw9dgPRwKfVfLAHMI8YQZh8I4aHiBcXB1qTAOJnDo7hP4Dw+QTh6kN0QOMpioPk3Oyn0KwdFxZ7LVhuhzLZz6Yml8rE8Lic3qVSbg8RSZTLIZUJk30R/aGH/eBE4mu60Am3qsaWZ6YMxH4LB5vlsI0v6ubLFRospVqWcNeSMrkX4LFsmzSxzfVf1ukToaDE3EbNpcMZjRc4OA87qvQJylzD2WLc0tdVMFYs34T/wAERVoNOow7AV/sKsPM/qF/X2gmMzXAfgqoflyOntCwrXmicS1tUagi34p9DZuV0f8AEAiDPwpuKqPzvysY2SVXwGJiYewyCOvmmYul7TSEf4rfqlQp3W92L+7Pzcqd8qFO99KlWexpc9rDlA7rG4Z0Nq1GXuJ/gtpRHtBv5AKvjnzcM+Kof/dUz9nU2CzW1gG+gamk4v7Df1Qp1mju4KcZiP3r/wBVx6Rw7jGZjCw9nBYvB1p5qT26LaLmxnYD3yiVi8TUdkDnuNzAVShiA6xy5ZT85r0Wk0XmZHQ9lWFWhTZVe1vEbLQbG69vwzqLSGva8uYCdVWwlRzYfTeOuixFbANqVC6plrQSb8panYarniaMHK7UehW0aVPJx3coi97d1icW/NSzOdJzvJ085TflWZ+Jkwjm5+57oHaFA/5wuK57PCBVJce8n9FiWYsljXUWUwGsi1ljxAZXd+AKx2OqDiF1U6DqhgMKaP8Aa1CC/wAgNAqm0cMxzBNWiIy/Wb5eirYd9i+m7r0KzYLCVC4ucWukn1UYqj+8b+qxHtdcCrUgVXwMx7rE4urDQ57j/wC3WHw+TCkzTDHNqOHd2qrYKoJ8PwvGhWOLMvHfH5/iq2KfOjPiqHQKnU2cAwcjK4Y30DVLMX+5/ihjqHBMcVg+Sd3/AMqfgq9xbw1GHqExuWpTOalUEsKgnfHzB9+PdjdbcdwyzuKOq4njYx/2hKw8/wDDUAfsBEiCbLIzpHmFnaRAE9giHeac/wCFn/Ss7pdqiRlMOaejhKpsdPs1CenyYVdsQYtoLItb3JVSiQJ1TwA9oBd6J3CNTieI3TywBry+4ALgi5oBggeJugt6LgltSmQ0lh5YtbuqTBn9moF3XkC5OG0gMb0FhcKpTfmaYjRYibZAZ1yhEYak8T8Un71iSXU2ulpA8VwFQY4jgYd5+saaq8LIA2kDflEJjqc/F1RZqIjRVg2SQ71AKNXxadIXOCLXVdh+Az/lCxNRuXNDewELqqtFkB3L9U3CbP8Aw2GnvkVeuILrDoLBVaEhtwdQRKrPaW8oB1gQiDKr9ch/5Qn1ozGw0AEKVClTuhX+Yn50A7jpuBCylQVBlSJQc2Cgw2We8pzNLom8ITB0XEA6Qi2x/FNPLIlGrA6jRMLPPqiwkOHKT+ac17YvDhZcOtmfBa511NSm+eZ8/f8A6LO0mPBohLuaevqs55lJMdCncHKbloEDpCAp8Um50Cpm8QmgQSSQshBn7kQbLNThOCMriBBouiDZeaGq6I674U+7PuDdH0Cd8KQijO4wnQoKaWFHwyjTi6zeiBfA0QmDqsw7Lnln5oOiwVFj4M3HQqQ9pcQ2xvqstPKbGQ71CAe+Ry5r/wCiy1ATOohEsfV/zQVcoNnPp5Lmy6AuTs5ydNfNHiC02WUlNieqMruoJRJTS1Fqep3QpQUfNkK6n5+26N5mVl1QBWZaFDVANTXGChlkInRPLboEZSo5k0sLh2Tnuz9Qmv8AWNAi2pBtdUXEsi/co8YMPN0QJu4z0A0v5rRueMltEWm7hfRGCytIaDMd5Ru0WaTaNEHMn8U3Mc2kfmhDM3pCqU6gzcs/kmhpaxv3oxCh0OXRXglQdwIsgRdZTulGVAU+6Pmr/OR7srop32RbqghMppbCcw5lP4IB2ZNqxCcHlsWTKbtJ7q2ampBjtqm1XWIaerj0THB7G3tqmuewP8WYSsz3OZfuhTEgy8jxdvIIMw1Cp2Ls/mCUy7BME8pQhzc2n5oAc55f1WQuptsHFPcKhdeBEqf4puUEG6k33Sg9soNKAELqFOu+24+7fdb6TBXVSFB3QhvyuRuHFFsIN1TWklS4plQZj96ZTdlJIDk+bHlKZSdZgI09Vg4Lsk2At0VIu1IPT/VF3SWNvl0TiMzhyyhVwoENEE5naASeqytdSa+fPuqwdl6riTnOUN6dUxz8rbk902nnpOdOitLbKVzSmG+soCycCgi1qICduncAgo+anfZH6F0WVXQIXRC6kKLIjoswlcQ3WaxKaG5C7VOY+2i5jaAhUBJNllcGnQJnxfgsnM2OZPkGRqmASJ8/NSy4GXQuP8PNCmw04ii912m9x3QZys8U6nohyRp18yqmYkDTVUrHKJ0TAA6Y7BZpARY9OqJ4umoqXAJrVlKkJ0aW3QN46Kdx9+/zsjdG+CpR3EKQpUHcToiLFdUCEQ7yQ6Jwf3TCJebpwqQdFmmTypvhy+iaGGfEgbgp/DaOnQhC7pg9lnaRVkAfiU3iOpmzZOWdAU4MayQew6qrlc1whztJ7BGk4SZnsuK4tbFvEShSdLdRYlFwtdZWhx1THcxKl3KsxjyWU2Qf4k0GylZllQO49EQr7wd9vfjfPzR92VCDhu6qVG4TKa7lcnMNtFNPzhEWKuRoiOk90wmTb0TWRyyELWykaLiNlOpGTbMnOEDwjU9kymZp6j4lTLi1wsbp1XQR5nRcKQINT6/l5IOpUyXfD+iZXBzw2IM9T6I8Om5mjRlj0XFIy9VwRyHpDk3h+iYJa7RMaJ0lOaZC5Z+JFSdxjdKj35Cj3o+gyiN11qoO4tKlOJTmFGF1RiFm+5WgJr28yg2sEQ0mUxzIKzHJHoSm0zOYeiYXGX55Qc51OYb8KNs55O8KkOZrLC17m6qh93ElVfHZsfinAguAt8Lv1TnjOHgu9EOZpfHXRcF3iNxdUnAiXOKYzpKNWTMAdU1jCOvdcQ+acHJpuiHSFbS6vundm3EFd98Dcd0/RIUqVG6dFNt2RSgQoCGa+hTITg5QJDZXNos/kEwCHGUymRbVOf8AGn5DIuE+kVTyZnzJ0C4hGbpZOy9muOqyyzSCjTc2p1JJaP4pzqgqQZGqDi6OxJKbc5YcuIPNcPT7/NZ5ZoUAw0x3WV9+qyEOCLza6PVSigRKIRUIzuCKJ39NxUbp+iWU7i07puu6grMi30RIsnCxUpzSmlHSfROi6NS6+Hqi8ZgLBNcRlH4oixPoqbzBbfsmkTfROjMTFpEqpXaXGJPWU6JNRszELLUlx5eqa4SHS5BmQ1Gy1sj8Vzco10VLK0fEHcxWV8pj3XKBEItNk6EIsrLohCgooKFfcBoo94b7fQY9ydx3AhZdVKhEmym6JtCeDC5blCYchPKLdU2eqe8IsfpaUyx1d+SzifyRpAkw4tOnZGq7zKLXmx7fcmZc/SfxRfTe6UADnbcCwWcGe6qDUR0BV9ZMoFqdm0RHhN1DPNO0Ra5BwkmE06K2+ESsso+/H0QK28nRW3BBwQa5BzZCdKcLwhC5paiWyFmvonOsXQmmSaiLG5RcJuh1QAzTHl3WcwIAlMnKW+i4RDwY8k2SM2oTwbdbNjqsr8tS+X4e6vD4h35JlMWvKObPN0ziSO1vVDJrfqrj1TWP5rriOMKAR1RCzCUAxHKi5EbgVGm4H3z9EI33Xbd1UjcQVmuuiyo9dE1vRU3CyFMoOKLm+iJ5ZRiQqYF7uKDjBMFPFxohUbZpnyVR1jY+acwgNeD59k8NAz+Ry6rOCG0jI66lcWmQaZBHkqrBlj0lT/aCFU4limFkkz5LNA0hZ7qDBXxJsWCB6oFQxFpTSJ3FHcRvCAV1Hzp+alEboXdCUdQV3QNwggbpmizWKNN1igeqYNUdApbN5Vr9E/OTlMKm5uYkg9Fnbl0TgBBgQqlQ5m9NXHRcuUf/ANXxShkLgYH6rPaY/wBFncB0ARfPNGUXTTlAEJwefzQMW6FQU0eZToUD9V1XEPQIN81mRahKkKLK6nfHuyh7x9+URvCndCspUhHcAjO4d1kKbqFmTk4Xag7UosegbdVUzcieROqDbG4KBh1OUAMtTmtoCuXJeOicXANBc7yTcud4mLZf5qo45u5VNsGUysJgMvZvX718TI7QnvaHNIui12R7vvXNYqGZYQMSuaUXaBHRyLTYLPKAMqUQuWFJ3Qp9+PoJ32UqN8ppUroV2RK80QfJFtwndQoUXaqbxdNY82lCpdrg3yhODo1VNoOY5j2Cdlnt0U6aoPEPt/FFjIacoPbqqjGiLjqpGfuULls2Qe5pmLiUcx6oUzlmZXEAM9E4OA6SoctS2TCMQ7VZOiDgpF0bkIEXKAKE753yo9w/MD359wIhHffcD6o90ddwKgo7i3RQFnCgEFdl1CqatClh79UZ1V5OipnmIEdAFxocNRZZgWkXXBMVIcBdZ9TqbLmsZBKEeK+vkuUDSNFUcc2WyFOz79Qov0Th49Chw8gVvRSYcobZEidxF1O6/wA5PuX3T890XUKSoRBRChAonREjVPpnyWYaoBSU0Kobtus3ism0TYSi4W/BZbgp1RpNmx3VJjDkF+6BaJFk65aYClsAD17prgXH0T2PGS48k6pqQ2O6bSfc5moEOblAko3ErNGXWAgwGYLgUan3LnTXcy5pCsUc10yDCDrLLf8AJSNxG8oygpRV/dHzw3yiNwKsi0oHc7ondUQV5K6+sgQst9VIkK0hUqqp0tTIQnlFlVzGAptHqm5OY2lTr0T4zZYYeqpU5ytzRGqc6COmgRY8zoU/TWyDDHVZ+nS6DGGNJTrEFcoJ+8IXjRZR6pvVFxsinhygSgV13TuCtvHzBU+9PzhB3SEFG4IwnAoHxBUndLprOiadEWGyJEzZMb4UHuuYRZ8VlV7iE+mcwCkwmM5hzFGoL/ghNphFrvDZNrCQfVNZLATHdZ3TMN7qGloPWVynSFBmZhOm2iMWIiExzb69lwyY0RyyhKlDQrm8kVK77o9w/MD6dhqT8j61Nr+GamUuAORurvQd1swU21TjcNkfRNZruK2DTEc4P1b6rAUjXbUxVBhw7A+sDUA4bToXdgsBTBLsVQaBWFEzUA+Udoz7RnRUapqNp1GPNN+R4BnK6Jg9jBWy2YPaFbC4rDYupgsPVqvo06zS75MTBiYWy8XQfUbjMNNGkH4horNPBtJz9o81s/ZeFq4ivXYBTw76+XM3M5jNcoJE6gL+jnFwVP2/D/1tj3NfxqeVuSLOM2N1s0Yz2M4zD+0n+w4jeJ/06rY1N9Rjto4RrqebO01mS3KYM3tHVbAwlLCVjjsO+licRwWVWVWFgMSSTOg6rZTKtGk7HYVtSuAaLDVbNQHQtE3lbMwdenQxGNw1GrV8FN9VrXOnsDqsPiqdZ1Y08Pkx9bCMzVBzupuyiJi57LD4Si6tXqspU2+J73BrR6krYzcI3FnaGEGGcYbW4zMhPk6YWy8LSZVr43DUqdRuZj31WtDmjqCel1sqtXZQp47DPq1GZ2U21Wlzm/WAm43fs7Cur+zV8Rl+CiAXevMQFg2bIwO0RTrubjm0fZ6LWjivNYZmtiYmNbwvacLUq4fZ+Mq1qOI4NfCjhNq0nRm5s7w2PQrC4/A4zGVKNbCU8HVq06vHyWNLxGWOcICwO0dk1NpxVw9Cm6sKnHAa5nBcWukAnsmbR2WMfhcBjany1SlwMrG1Qabi0zmcALjuqWJwj61DA42rUpYk4erhmtZxGVAMxzc2WI6ytnnAPxRp4hrmYr2Y4Ys+W4/+GADBP3wjhcFSr1dmY5r6uJbQZh/kuIXO0+PLH3oYXCUKuIwOLpVq9fg0cL8m6q98TbK8t0E6qhtWlVcxlSk+jVNKtRqAB9N4vBgkaGbf3btDaXsTsC2XE1MLiTmDYw2JEVDftAKxPF2zh8bTDcK6g/B4KCD8hUe95sNPEG/cv6R12YKti6LRXxtZtPao4jTFGk6nlOt5FLp9ZbS2jtnGCm0DB1qHtLamYWxrKZost6QZ8ltTB4CmMXgZxGNrYmvjIqNik55Ja3W9obZbcbs/H4CjhsTTwf7Jr0KFHFPoOe2oRDGU30j4O+dYquMLRw9FlJn7AxuCqOEANfVFPIDHSxW2tq1m5sA7DNGwcbhM1SrTPy1bJHgJty6ravG2JjP2ViJwdKtQq0eJRz87Ww8c8FvL3lbSp4iph8Q3H1KTtqnFtrUnYUU/97xGlxeOLI0MKo3ZO06VbA1Xvr7Xq4lraFSm2oflc9N4LjEiNCv6RVMHha2IoVK78LtdtdlMmi2u+iKeTnyEU88nvotrYint7Ds2bxTtjI6niHPpj2f5JrIqXn5MiRllY/Zm1touOz341mOrUXtxDX0wWBtNrMrw8gwCJEStq7N21X2g/D+0sr47FAUy9ubDsqVC4Vad4hw8Y1W0cecHXbgc/sG0uJ7OajP6xTDC0Pb0BBdIB7LaNTaWztqjZNR4o0sTSfhC+jxGmqWxUHNknlg36rG4bE7EfXw7MuHO0qjmggigcS8OYwegtZYvDbN2ZTbhGsq0duVcRUgttSdVfBn7BFlQxfC4oJ4VVtRkOLeZummvoq7MBW4GFq4l7mlop0ywHmtPyhaFtj9gf0dnZ1VmK2NUw+bDvqUvlgyhwn5C1xHxWmFtnDUNvbSGDjGY2pnw+EL2SOHSFNge6csmJN1jGbF2ZgMNiqLfZXtqV+LSNRtd45iXAOZ8fMv6SO2ZwMRicHSLdrYjE8M0C9lQGq57c0VNCTmA+4rbOzti4rD7Q2dT2hx8finHD0sjZp1ajn5jxH5SD2my/pBsXY+Lbs7ZDabq+OJw2FY6l/VaTmiXGXNa4yJyz1VTG7GwTRs3E58JtMYqvQxFWlxMXIIeS5jnN5s3Ujsn0cFjBX2DxsJWxzamH2ZnongNFOCbuDLuvlBWMpbKqZ8HimOZtI4jA4fD16fFwrcuWA6ocnfl0usZs1m0MRiy/jY7FcYte8Pe0BoYMxbbMYm1v/kX/8QAKRABAAIDAAICAgEFAQADAAAAAQARITFBUWEQcYGRsSChwdHh8EBQYP/aAAgBAQABPxD+t/oUWXLixfgsXzfwUr+geSAxqISqGY3hmJRuVGrmJQsySzAIWjkHJesvU+sdTPVIWdo0dlwNjpGXtIrZB4K/ifEWCIeZnSDTuIr0I+KpgicV8MR3FaHH3MhI48ElAMUyIPlOCEgOQf7jjQo4CUuyS2hgzCjOfMqaXQvkKY4ThfbqFR+jE6kt5gnDbCXihT1xCG4RGDE0MtGpYBp+SbhD4fl+FxaikYYWLj4uLGNotx+BcwTOCoJUowQgxlGwjNBmEILRLo5IAhyRhhFezl2XMGWbFViycYXYw6TOJOioNsEf2QYYeHN+mXZQP5OVBkdHIOefZmJtKGR78zIH1L/cgikU97kgwZuMygD7k0/T6PUvQcXWiAzPFEXhsItz+3ZeuMG4hDkuUpvXmWFWJQ3iOmIk2uekvD4iBmPZGJ5/pD4U+VlxixfC4suMLDMflmNxTH4CAHxaRGG6AY1QsLBEJF3GmFdeJbxsZO1uYjKORseCnfPEQl/Yy2jQ89l2gGQNnuXSqtb1QEYiu3Y9S2gu69Q5vR++fBBSEBlNt4C9OopWIot4lnzWq9UEY0LxNsd0XYoc5l9c8PJZdMoOTL4iqbEVzujPiC2VXmCqFRhUbFdRLy28MdFZQMXVlx24QWzsOyAMf6Lly/hYsWK/C6X8lqL8EWNPwMEeI3NIsH47YreY2iDMQgQDNEFwZ/LULVUDDtCBUjNrPHkAUq3jUQjZgvJbRqf0xaopVlSuObNNPEBXD/qTBByHVvD7hHY2b6M+Yq2i8hbL1GrPUzOYUMVZ3hcIgtKDNxLMDl8pTOwtPD2NS8g5INQMqQrJb88YwuSNaBnfITjDeAhmd6QMoKPUrWP2RWNjsGCfmCMKQzPuKHH9Cy4wMuLFIy2KL/QY/JtBs+Fr+gyRiUs+ErlhMXMYS45ajNDGjNwJYkWggYuDCmOMSyFvNjGVRb9S2ycAiFTtc3AuhAK5sruvJcYC4aOseSCwGPLk8QVVxiteB7JrjiVv8QQA3bV0iqwLL36lpALM2vYVtvGBNKG2khCgKP3LYxp++Q1MUgeIa9WXVHW5cq43UfVlYxYxuIg7GOWcR1WDLDMvdtTkRhcAIkG7I3jojD4WXLhORZUfiovwUMUUZpi+KPidiZYwu1EVuayVQG7lfNRBZMM7jiV5iXuIUmZYghFXYxrIPSb1F1Fpg8sJU/a36YDQy+DczaA6R4eaQW0Ja5ZCYFoUYvr8RUZER0hFRg7fN69Ryisv1ekJbtj6mUGr/aFQhnqpnpS/gYDw3W6jC1Xx4YzSNNhKG0xvzF1VR2J1udMpHAaZcsbSE2sRwPPEtgQrdwgDiZS6vxFg16hfaXjfy/0D+hij8SD5qi4gRrFRvM8wRujWybM8kN53EXLXuIqoLI1MIVLFMEyeIgNF1UpS5G0jMhQyeI7quU8YGnjCyQYIsMatF5cTGhKcKbKewmWCvYdwVG1UGdGScYGKa4xgShXSG6JLddjfLDLsuXIMZPCJvGDhgbOngJS6g8qg5Wy5naPXmOI70DLQbcS0CWrL4aViLm0Zd0fcBmRW1HckSQklyhl3AVcK4i9hcQ8+/lIpm4NS5cWLGFGPxgJTEOomIwp4fFk8yLFXcWMxhQTMIOd2O2IbAzH5wioSy5m+1FLUvkuUTtUtSvgRlVYG8BMyw4/2CFUOCrog9rng4HPuKW2JejAICUeV8ogONanylEUB+T4i3rdzc5+IRFgwbtsY0awVWKGaUiW/BG1Nn7gZiR2+GfutEKbiv/EXYUbi+Gkf3ic2pYLutlxq1SlCNzkhftuOBiKQ07JiUY8k3F3smVhNwal+sQGal5+CKLMWCEWXfyLGCDKuYHxUax+IrIsv4lXEpULvMxUqauVGdywkErBUqGowBbgCrEUzFysijsIaK5yOZb4MLAMaXufo6OYQRZ4cT08YSGVWVDO7bjJ4CFvOrAwxKxptAsKXR74114goo13xduINHlknTflBzDCrg7T7S4HoHfzAN2irAYlpZWcTGCuEfhVnYKCuyi/MylRiXFYb81Lz3FbQW1Ar3Z4lwQrW4SgriZhNnIwgdJEfiJNFI7BY0Ypl8GYXUAkPhx+VBjCjGVD5Obf0DaKKIMQ8zYmFxn2msxpklm8qTsl8ggkBQJ5MbpwdRyD28wM1gb9xIcC3tFcmtFaGCr2w8RRJugun1M6262ufYi36WUyCWyLdu+iU9HwwN23RfGjkAIlYuIePCT72V1gmKgDv9l8wlhRoNkWcyonWVdLNUTOLkH0R/XZ1lJsQO0tsekHSzZ/JFg5wZl4D4mAwMsWk3CrRqU6FQxi44vxCqYnTG1M2xqGje5YG9fA8XGNoUZFfr4Yr/odzUX4Y7hNMZkfAmYCptUCfBUjuyXuowjhdwHbqE3HTirZErDEu/pLcqSPBQOxVrZs9mbVtwvItkfWZICqtmpUUpAkFwUvntORS4BQ2u9QmCj0EqwIdTPb6lCjmCjF8+oxuLaMFtoiPPDhVQBYNNcf+wxBQc/6loTpt3D1BcD1B7Y6SphCVygfhGq1SGXbNPmBgwmmX84XTF03FFtNYiVhpIfQcjWL39kodmSLsxeY/EvYlQLiXEsMTMtMMD5BArdxj/TJuZSVKr4PwsGyKOOosR8YMszL+BRwm43LxWWbGBekUWZj44xShjbblibFGswtGHZhNe2PRXW9m8yrijseuEpsb8RkAs8vlRiMuaI2gCgINC2ffmZ8WHNr7mFC0pvGx4IxC43TyDkLaJduxiu8pXwwOhxFXOWOjFXiFDljhqOCXuAFbHNwWoNZix3wvkrWTDcT2jC4Vy5uPV2rEUqdw940gMPuplWBjGF3qWwK3LmLbmYXc2z8LaNxF8JMZfwo+VmUqCJMEFsyJVxSZIO0uLl7OSqnzFpCCRBxGtrY8gxRqNCiMTsBlXucgmYpA0zKilqwkoaN8EYi+jcGtJvA7x2NI0YLwrzG7m8B09EeCo+wgSVlNJI/8R5gCjfhXg+qhXAdOnh9SqkuvaD/BlxRCi05zcQUekWCRYBACNovwjhppWR6iK0ixnylKemXbR7CBajF++SwgZRO65nWibiMHsNVS1CJWKiY9jGsNmWSBe7nvgjHY3I3+/MHTEJMSmYYVsfgyfK8Qh+B8rjaci/FkLJjWCQtzy6lozu5EyiCsj7swDzGUBJzGD9iNVO7myYxWadMXJf8AOYlbl9QOImuoSgSIDyv+JduCA7DTLU0aWLOMq3LIcBeDwRJtkPBWmZsUwG/g109y0bBtt8JM9yc8SZuZdaimE9e4/FxV2kWitbOsAqqelxN2ncUKRO2NwdQL0hP1KZNQSxmG1MlRsSO37KzOyKIdhW2EB0cZYK3c4JG1EZLG2ChWeCazGGZmWO4oRXe4GJqLczPkZ+ARlkco1gGPLUsxAIRaXbqN1UsGYZPjFUU3Ywb0S3ogDJyLqbqKSxce1GCgECSeHr3HEJRQymESge5jpnOLSCyVckYHpb2Xq93sxVSdtpy/ZyKF19NrS9e5UgogDazTxGtQxA73ti5pqR63+SLWFonC4fuYvTCjtDkaZove2ogYRaEzLjqRWg4Zl5WS5k5GILgo3+IIGwJ3c2SqzL3RJTGhvtyhDuJONsJN0k2ekybGAXDETz4hsS0vNXF/rH9ILuB7MGDQO2AJS5SLUsZcYXwYiIRRpFcoxKGWMsosXcW5YMGkYLYuWMqW3mNJaUykxYDUQXDwjrr0sBOUyhU9uoNrph/mVYhVRrB5gfsBRizkI1iuKHadbhL6pM6OfcABs3kPIV/EBjqejbYP8k1D3bSj8MR3yxs8oHb2wt15BZXhgXBCLsLeNQ3Nsat0kOAchVzxBEqwrwsWMb5CDfHIGRtIOVpWaTATsxeBIg3cUDNLXHCbgZ5D1ZV2OR4yjkeyw4Yj+IniVbELE7E9vhYSDOXD1AJeRwQAI4YlsxYajFseIFSyrlhmUHNLCJTEJUUoQFCxiGIPmJtsYZ5CMsVtl9CZRgsBpyO2hWpVuVH+s5Fv1kzdyUuLaWmdFxUU30dQbjZDQQ6rN1joR9ThooKgf2EFMwLaK/2kcsEbPF8j2U5h3/u5TCpAc3Kr0h5X9ttZvrBnbMx5VKORQVXCNzdHmZ0d53LYrALuUPUCn0qOEX3p5RCTayZKJ9TkDpDiWwNHw8ULLtQLNCRLgXBqXgalto3imGWlXB8v4wkdwUCE4QblokAMym4qX8K0YRJGVu4AQqpLUQKgyzEr5hCHEHShEm8ZwMOoSiSKrtd9QLUliAZh8C9cJrRh858fuA/7hGxwyldItR6T9Rxay27dFPlOTA5FPYsPQWIiXNjA3oZnhVEWVdh1FQJg3pesukMPo7QJMBlqtdFeo1Lhb9CaQmhGUPEYMvHqUjK2IEhwXmJfC89YuXlbuO3TqBMdTRdViU/cdcQYD1Gb+tTALESYoXiGE0RikIZKEVQlMrLJ9kYoTCZDBlxhExRNzbMZyefwVWQgUq5ShL4YyuGI8TLAxBlnCMKaqBAcJBzI8nigj+2Tknkg6YKUQtsLggo5sYHNy1VWQF35fRE/KoXn6LH425SLELsAtsDVF9zAaph7DK8rNa/3TYX+yENfggatNW8IhzwHDTzwEsMLpH9IDaALQmNcVrUwsi8duNoGYINQs4i6sCooGJhrTcTHvuWTKSt/YhYbTUtF4lFux3KzomaEUS4rnVmElLgyYgFkG8ZSPmIMtLguFTNmZG5SOCPFQc/DxHUWovyHUziQrAgywxwxLNRJCqEsBVgskSiWNIv8mNSuSFUQvSmXvyI8DlIG4bJX0cw8yxQBkDcDzpO7KjxH4qJKMF7Q/SMUR6AtpCPAkb31TDDrOVT3zQOBCXR+xFpW7vTEnWQO8aC/RMsIw5bu+4TORgFVPBDZysL2bMz2MA1SaYkRwFQpYmGNxS6oYOw1Ed8TmhERIqg8Fi0LZW5iYxcxHOJUHhnfwR4N3mDZ2GCVO/v4RC3GAMsF+vhucRWQNNxFzCMOcRiXmX8V0YJcHPxW7I0ajIrFRKsqxXBiGjKXQtBtIGxl2WWBVDVnDyOQlPMHjOQxopA632QKwM4I4DHPA8RsjPXr6SqgGoOMS0r+8GCZONeV3uXRKLFqNwAUDpas6pcAusVt9FhiR96Vq39hl8RxFZ7+hhJXicLd8OR4KKy7Q5M64/mE4N5LzDrBnIosMCgcsIrVH8Ts3qW0MQwwLDlnFWZcL5AHh1LmwjdQrvFPI6XBYpU3YrTkIt+2U+A3fqIhDOEbrs6zB24qbWK4sVEUIsRYUJQTJM8yhi3DeUVRlHwElkUlzU6EIgn0LgfJX1KiXax3huWcUESmi4dUWWUI06JywMxwW4XA1pQo/wCIhEDGmY7aRgxZXk8sVS0S6+esHUsFth6LE5BO/KeBG4Jhakg0qBTLbb74Qp5lNtGs+iAcOb6+T7iiLZedCCBMAL8PMAXdZiALmw3C0cIQ3FbBsmSuiB+V5BOkZfNOjMAs45JdchgFONT7qHkbQrl+YCgaRNXllxbemK3UQx4WSiLSE4tgimMnmJVagEmnGpVVjZU1FKm0MRt/McRbjkgVUGvhMK5x0IgphNOQYSGSMU1wktL4slmv4oW+XDYdUxdaalc0JVBctUVXNSpNtgy2Y2RXryHuZQbj+eE5sMnWByTVKFNAcg91o5g6+IA8tW6BdUS/4yAqlg5yUmYs5EDMKUb9sYRGFJkNMyiXkMTCzfI51owwaJE2U9H7JSRcBOsNsIZNsLq6MlKCsy3u1OItZlSZMzkjmSiDdzNURirdi9ZKQq4sgaUCBR8LmbcBCmCpa4luSLXuI+UXqdmY1YWFWZHuYaTCZ0Ro5jytkqWXkWHwWDFxVzMEcFxWXi4yrllXLpQo6hBhAiSvRjP0DLHP0ZH92Zoxwj/VF5iv5kISlETTG9QTi1f9m48mrpht5MkPINhbUvkrBelcF7mLFKCHrlLapgdTiy3jta3LdEe+hmZeAtEeGRBUOQm4zoxQQrCoPAVeoNfhJQ7ArfgDMKvtd3nSlpCdBoqArZx+iEQoAFES/wAjRGe9IgTXkjSoTDQ/vMqwOqAfgjB226GlcXeP4nYAj4VF58E2MsjgqlfoxBVtFG6JExk1TlTXL5WH3WpS/YF7wmSAv2qYLM+IasgoMew1GSi/QiQYcFJ9twBNYfylw/8AuZcLg0xdmGfvw+IgYBwktySyxEmSHliPKEYaYLi3iWHcytzVgSRT6ifbGwFwTFCEYw0kQNQyotI6iq18NiDXqImJXc2foZlnAnCFoIDTr2j92QlcF0wy2MqY3R9EAgNhnbwEGjaRX4G2KC/lEUqoJmflMeS4/kM4QMUB1V+0KO1UvhoUepU0bB9tSyJdWw/tBczIK7m7NZiTgVMFLMCPIjOtXK7reo7etAZUuB4itk4MWdX/ADCipvLpvOU9b50tn8qjYkdpODCRiKamQQ7GLAJ45B9AXLMcXIrboIgrKgVr6uLvYFZjhS9BLa8W2q+0Zxu4RztyJQuVtKARekO8SFQZVWBY4M6G5dqVR9wryYOlYhknMq71fRHCcOGTxBTCKFX9tjDH+zBlkTUCYXR5MMfnCPr68QhP/DjwcibKbVipuKFEs58I7aht9xXAylwwai8QYsG9R/RMmolDxBCDyMYwUzkmsqrnqElExuJdxSzELpds6EGTss+jB9yXIHAYMCBvJPtIppC214IIeqS6QP8A7ZYFXkC2Cv8AdlDI2pf+Fiou6wSwg3R+8o7ajZ4JV6zNXgslpW1L2xyNjR7G5mK4cnEN3zA5EjTgBz7YSuKXwebih4DcGqeFlJKalc1s1iO18pvK+hBgePYzGt7QFpcW/wAH10aYHheNtV7phA68Ct2BSw2PfT4YAWtwBdtaza6t0mYShdVepkp8y1N1W8MkEl8pkdiP3NBsqjNQJVwKgINXtLjUQ2uWEXk6NobqDkL2uf4ImZVfwVoIVp8Ch0wRhmLC+FvxMTdV4lHcRwVq4qKYkRAQZmmDfwM3KVHMqMUZZVeUZiJZlmHMvkQyjbRHuX0IkwaN2/4sQPZ4DiZLHrynbFE/8MKxbDMdf5c5Io/cmZ4M9Zo6woEWFj1Ev6cbXF/kM8nZn05I6cC02U52QQHo+kiBw0DTTTUJXZCUpN29Zg347rLW/TD2rGZ+E9MEaMArB2D/ABFTPZdaGH5B93CoJ2+snX1C/SFiJ2nSZy2ZtnuiJz1wlZsekYKfSSUf3LXKIkBTZWCDo1BGrKsVf2MTYwIAX6xLkerOGbR50S8TCha0/RPH9oCcIFY1psuHwowV01JsVbFBFZEmvqNvOCHrCdMOD0wUZkA9enpjZkx53KlvYuTLdsswlZFohnMxiUNQzS4yF8zdzD4jBm0uDMIYGCkbgGGClSm5GpiUUksS4lNA1qsGPUZKBKrftTPaehX7CYvS3qB3LuKu/ksAl6agfBQXw8/58A/uDoGP3AGjeWr+nSRYaLWSzXXIbcrFqAKD0EslAQtbaDQMrJzdLBdkXIjeLbPRFioUVtDwxow7t+DPGEtqgbCj2ZhPMM1H4pRbCCcolKd2PlItRNLQIv7QLmknfuDOTV+kVXOhKDNJu2JMs0Kf7kczbSZH0GiOekrMnY+ZeOR6O0+0YEXii/VLXkarWsbZnTIA2ADAXh5YFrbXtMLG7aMqPplLFteu8RJy+bs/2TcJK6p3LtlP61d2swfgoBIFKNV6v8R8q54DyCeSEfgAnR9kVyIWBfUyzbcws3AmypXZi3M5YYcpMIuSeMGK4imUGyOOMsMYd3I3cVuBCwGWMFDsRIBoA8MOkB0JhfEaDBE6UmwBzKO6lBdQM3gifiPVO7QrEet6/EODiABE+46jvlQsGdLYwZ+oZ+2vLmRwAqXBJnFWXVnkdzmoWYSBVvC7WFGSjBbi4prkRLjAMEFjijKxNxdlWYrm1mAzRNKTSqxHjcrKpyNx7IBi7Zjd9TS9JUBvcPKhqbgOQ2h3hdHQoCChkrpgoIzKO4goAAPohLjAIm7I2yNlbcxe7WxW/UyZSvZWxP0MwBk4puAr+oqPwQVYmwhZ2mLxwQNIQSFEbGGxv5bvzK6WWgBe9QF4tquGwgowhcaPKzDlNdxcUqAlAxBZNEcZtuBL+AXB+NlxiyVBSILmQiK0yi+UXmEYsOoLHI6jqAAjQUHFYhPUMGL4Sxul2aWsZQ6FpCxlxUDTCOPqMBlqpBC26mtcqVVWwOHF+pvlYHIZhGxBJ99OHIqrFxUa14NLRMYwCjl6L9kymqgBpe31GLgcHgmFXyLqEX79xLv3K2B18xBbUQ9qB7I7sFztLXAkTNEdS7CCK+YIeYo28scogVmLRSYFMS48IXJi/W5W1iW0POJcMxCy/WYFQxRiDeIJS/F5HxJSTKbdm06gy6+BRcx4kcc5jHExRouGyFljPvALjcQxK1ccEeRCIx6RI1FY3Aa2xpZQxqqTW1ROfS6SCcesnY0JuMv0g1snTYwWqN7VTCpyiUaw+IYu7Nr6iFZpnXdf5QS+CUea36I5auoGCgj3bPRxiweWadpfliEIP0FxVhR0nFPEWlbtA0ERANXaRgNqMsTZxI7Rr5ghGZjcuTlj0dii5oumFWLi7FsAvbLADxCwlkXFmoNLIQGY3mbM/C8EK9RZDDerzLDc98yy09S4faImsv43FxESmXZ8BzFtgFlhGPq1LFRcIKcw4g4lI0KlE9agDjvFu43ehceYk1HedeoUHXSCBjYSs0bQ8krLL2DxCCr7XIniBIbOjShrMLtjSxFu9RkcAXGlJ38y1U8gDnxUAYzQwtVl4ExSMUwDDK3k/GJeyED7GJSku6C8wxwN9olfQ6srCIGeRvIYwvHIw4Dw5IA8qBblRHnvggu3ENYuIGKlYrUHIzjWOVuFy4AM8bmZuUcwSCEWfEoIkqfrsWqMVsjT8pbBvceXHJuNqOYSogTuaYJTJ6lLYlmcsDB3AjADEvWSYJZpfIgmkoBIqojvqOgfZBpTRCvwzAbd8ufQpGlMUgexLgW79ER2ha22E1ELZxHXKOu3O2XdUDwDb+4QVqq+FeWHbkLXvi/zDRsY3CSNW4YD3KRaKxqsuwdaJvG/QgmA5vomszVk0s7l7UZNJpgkYbTJu4tbDMRLfCMBCUgRbGIW2lxqo0ZmtEKRKuHvzAq75Kn+vhtRWKIifcWoz6is5nM69SvVxq2KdF4jnAXLX5jjKJkTcuWMfSPjPCLGmWQbzNrlCStkzUi7ZI1/crx5jATMWMwQrzAKfeoCl7IopHkcDpaluXsfMxTiNn8YMeqq+0wArY6mB51puXUiWsz7PuWiLUGj+nYCqg6rfrKHW2BgAPiiIM5dE7PVsdFArxmOrtURVDFQzw1L+KK6tG4NUVqXDLIrApFEQPESwvIwOHEwE2EIp1APEWYbY1kWAJE1EgYxNg/URLNQFzm4gslLxOyHtDJEvBMn18KxouKINvNSr8RMxhyEBjJKF3F9wDLqGGGmYsTUfwTUXcIoaijEZM7QOUVw8rZBhpLwesBFnXNRYeiJv2bj1/3ysEAxL9iljLo1qqMEC64SUZDi/P1HtFrVZwxLTzuv+WXeBmAHiI45oXaVvEABo7Pl2cEPgr/lDzPCRwFu3GOivgbjkdhRw3cbLDu4EpZBSDculpTyV7jbtP4gNLxHKCKZFEFdK+WGGSWwTYUwlqavcQWUeSSllSmTTEG0hVgxsG0PExTuH4SSCW5dgTX3ATGFqFqxcsi8i41Kbi1uJ5NPmXwisYpQVg7n6vgAzHCEWELUbPsiqajsUllRN2TDeBfJsjNTPcaF4Jcyxe44a8EvRYwRuwqbltYc4zC4W656hJm5E9w9S6XkEWbAlKzaxYaoUH1h4jXiwOSovFoIq2vXtZSIlzdepjgkYoMDcsSEOgFfyyvvQUdnf2zTHMN9p6mMFeIS44Yrr1Cs+UIXAOdYQQegmJAVVMNQuVeeTMVlg01PQXKQfIkIoVqoBzg+BgXKTJGrIYmWfO3mYsIpOxqwhjqK38Vqaxw2IYoy0jYGICfFM7KlSAsYjL7TKSwAimpSaZaWvRLIwQMssTEwoUvEMxlwJh2Usgo0Q7xlZNzJ2aTT9xgD4PBGhaA8CgPl57f9EGa2M7TkybWclX2F3+JfcGzbc14+4KCzt1BobCem48TzD4tAHnBuIUF1v6ldkux5ZfwqRjdBQsCk4P1LP0X3sESPZYLghidi3jcsK9wN3u50NeiFtHAwBDqiCsuNdS9t/CL4hY5YTBqaYm5mVHOJauPwINMudVXx1loo778FOxSmSOm4/AXGLC2Bh34WfoexydJNoRBjcy0ajAmkjL8pmG5YguYYDIkMSz0mFsFMbFiP007jiG5rEPywm0zkZMS0sITxCESWlNQssjcbseCFEuBfsPsjBRGM6E5L2R5Zb/QjMG4SXekeIAKbstZjEvts6Vsw6cGD4uBYhkt/mBb6UwxBsfwJcIJ2sxKLw+KiUw1KsaYW+TbBFUTM32xiDDJFg0zdRKxr1DuBbmRXIZUXLqxllTJRPSK55MPvk1YzDNSjhmBFIqZ5EyijjFuZVIz3K5RMtNR9wbQtIvUYUX4jme4y0o3EZrghotx2kVGcNmY1zpbpNQA3SaYKp8aYkFDD6mPwQxcvrIaHz2KXy6YOUWnwfazMGchyowDbGf6x5mdCgy7S/MMSiGLt4vHqDhsN3nVjVhSR2miXXaFczu5yNLdxbO/VwEuZLVxUOCbXCOLEW43AhyPiGy4g6IZNfUsprHuJbMWaY2sobtgEUTJLVS4umCE55mDkoHcOvpKKr4LKWgw0t6hExHWYiRxFa+5wEtU38R8LiPMvYuYzKJCZyihKi0HTAvDNQYY1HbxBCwoO0RomsQJuUJf8M9QYSLSxDBHYAgpWRiwG4oZBbbtJaApq9XMJ3OXJltzS8/HiILVcDz5uO8oV7KZawVlPcBBZMqVRsJfUKwZXtwA9e+9Y8XMhg+JTqijVxRQLVwY2GeyIgq9sW2uLrULQDUWDAeEU8YvBWrllMSxFtRb5iNfIovNT7D5lw5gEz7KuJdKlXMwZQtsAJkXEHc4myUGZfIqxo3GuowqNM7mDivcuMRPxrTFGUjKJfEOJfhTE7uU2MMy4xslTTqZrhjHBfUE45BDGpbBqIGGSPZCXKe4biIcxqobkMTeVWLaIdjZCx4TZdNV4lIU/2IUF+vSNgiqACoVBAFkkO2qtr/dmEgK/wVGG9gXeo8oxm8vZc63W/liWJcItApSauW5JBTAyHKSWIbdZVtvWMEAErDMJ03qVVIYoPHWDAKCAu2ApAmW5a8tRN+IxeXItFJmLREAzM1GmWWeZ4mDcRUaS0AxQIAivxkqK37+O3wU3DKOOZXrEC+IkC8IuadxRhmchLp2GmKolBiEOncuBA0UsnnHsm/3WYoGw7JY62oa4Ciu60pL5L+oRoPcybSmLashd7MWb+0WsHoGIRCwtiN0VuhdD37l2JHUraRjREUZKfUAvrC8aFOSxAE4UKXFNjQ6x2KMJGV3+IuJVcTyKgzC/dilQoHRLSA9ODBpKXJC+wdynjMvaarnZiAHvrMoEMgdy48QUjC1VhMHMMEMwLzEZ1LDlkZJRLsgZPx9I+86WME4lLiuLnEJWbfhZjYwL8d0/HNFotZgpYwjaoaXFMQNCbgx3UoXOQxTZyWy3THayVcM5lUvmPahLgJmZFi4MpxlcZtkdlDk45hnwAOiC8B/Iy2cU5eS7X04vM1ArLVUdqXaCj8pbgFIC7HvwxsgFaNHGdoCro3Np7aQ0OIIAoYCnMNbQt4wRFuVt6EVgoD9VECmlhep3C5nRzywuMeZiCkISUGkiQ1hYs2iYB6JcxE8wBUUGF/UtdRAWwxgMB+DCJuUbuAltMoEW4lxWWGob6iRL+CpixVDCIlooUMMYp1LKzTK6hiHwIWbTkjOgpIZlZWoQvnqIKEOMQmBgLaZUoWumKvnKRgPahWovRNoR3TFZRVAyy7MAcqVuIRqHcBjoCDSoy3jaKUAYtv8AiKw6m62nh6isAQABoiggEYhFcitnC0pPNynKqH6CyycNb2BE8ov6IqpzcKyRVDIJXslfGjPyodQvuHgR7DTHSnwUDcw2weIIRZYzQzECZ7Hl5iUiHSy89msQ3Q1BeYqYr2Wl+X6ix9Q5YsPKXJbUWjHxYESop+ozYY0qfww2Fx0VLLplVNkLSEG8/siwciWIOR+AKAItW5mq72Q/TUqhaGmYE+xG2nJsDZLWWxBFYq/pguQ7miVo0JQipQBadVCgbWmVzvd0Gvv0llUAttZ8BMIanjH3cscVQCl7hRKBWExU9Q2Nwvcg0N3AYPh3cFKsbrr7g42JVAQjSM4+4xUx4PMyOjhMcoTIUM4ieLiIjgRjrmFPVS1swdwDsR6imW1mCXLEjUV9TOD6ztOMqGJ5RhCoYldipzBEmEBlX7jFkJPIxsbrl/rCbi+w9mmZk3NAio0fUC12jxXCqyHtitwNiRi00puEKzTLuinsLaM+oao9FxFcjahX0ouzRMkIegi86mL5eI9K/dlP6GjSv9R//wCkBY5BylXm5e4oUF+CDMPlcX3UEjVFogi8vGMxUEDn0wz0LtAAKFrPIt60NXTcuA9LKhwHPMdNIHxGL24rkUnJdoVAJdYa1OZUvtLNs5XmZUw1UpiZwjlKrETL4m0R5fuDn4MdxZ32GH1MUwKs9I2nTcbTI4i0+NEWwZvzHWiTKVGV7jkKy+yxnAgtZC5TJEmGPeZIlw/iNzZOn7IZaEZjs+oqRdhJlUemNERSERh5dEoWtYyF03KAMWlqKwL+5eoYEfUA1s4hrdDAyXwWKJp209yhPZHDDqkksmAGYKKqRXuM6DzcTRWNLouDTTUrnmGsw0HamFu3/wBiCexdj+NXKsUEWUDpgUrWWA+PEZtuZ0ceJd0xBLs+pRWDPVmtSlx/rEbWGJvB2WiwcGxhVYWdlme1EQlRW6i6DHEb1LaJd9lxW8StMvOxDKEwQF2QDlO5HGdxhPXJYepa9MeqKWqSctZMjuB1hmm59szx+ZUd30lOKSAEp95TKD1gOy+YVC78eYoHyNv1DQXp5YCELSQJUAyumIB3fNEfbER4lx1kwIX63BFmzlQGu1Vq0+uQjhFKm7plq+zZl8iaiAu9eyNNmNmU64uUrOOShY3FSdrEVoXFUFvuUtoCLZvqXm0KYBukIGDSkQtIlHstjatJYmItgQi55S7SxjQ/MMoIURTks/N0RS3EyEnrslkfIUlZK0swMy7ZEvB/EWphhhLAOSEByJwHxyIuUUwsga24xVkamIKjm/kqI0t7JqCm81iCaSaqCtp6QgkXviJKPqgVMHTsaUV6ZaxFrErb/EcdgZdfiEqrAAqpYbNu+sbKRJdpnUIr5Bs60QIWuhYUD2l17vUTzBZNrQedfxCEKoFkVesWgf4IZpSz38MNFtm4IBfuD/gRmENeIsLzMmJYcyyGjiCTOJgivYKtRAYfzCc3H1Fi19R6RMDUUnEvUw72YLPMWM4yql6gLPOS0SmFyncsuo0MsbYnqIoY8BtX3GVRsYIJErqDIH/JUOTzDKBjhppqUukM0IkdHYTQpcNw0YvOA7AiaDzxcDQqtIxso8gzKMMDAgv4hpa/wlBunTen1McybDkPAqizojd0u22WDN2V/iNgCyvNhHcVi2S4DBuX97WyFEtrv3Dt2nEMFLRIjATPBmCz/EsKkBpgZiNstkZIA5XNRFeJY1BN1FSzBZLhoyl+JcbSG6jQiIAbn0jtlt/F1iGYn/x2JkoYQK1u5L0IPgwweDcpFb1yRfJ+o6jXNTSxZYoEVK24oVu3KPJlqpXOA08YYGretVtXSrSPvoQxwXHppAtUiRpbcAOWkExLKwhu9cQgAgrFcKuy8AGtEhuy2CxbTKyf45dThRSNKQt48e5Kx4SOOIGnVF8bMqiIMz8Vo2GCL+xl8oAl5+dLxsgx9ealxbgIpkhLquelg7U9Phg+lUtW4EFZVjTVXNHKB3WoDcNr1UhNrNREXuyMJ6VibJUmN7GVgqSoxqFLhUVbiiMKOsYX7c2xJIQ6cyoHyLopIgREwZuKm/5X7Q7/AJkcskjZEpZYlIBBF3iBKbVgFIj/APWlG3sE8qi1kDMLlf8AO52LSoPJCKYLVCSlkVpeK7/WXzu4Y6XCvMlv5Uw4DDt2ZI7oWliV6iQ84EAbJC1kD3+WGmAy9qgv9LvT6d50PSZVqo/WiDoLWFDULBnhqh6oEWLR2+rZEwugMOwXm+0a9n1ysT88SM3uWrtBT5QrOIuiyUuhtsHi5o0zAB6ynl+aj2aj3Xv99vubwCr+K4inoqZrEAGvc2dNynlYYfo/X0clOdzKJkUks3dzfpMxL8qXhBMRATevXXqKZXe4kYhpzgvqrmKIFoDI6NZqojCGmW+pixmeXAbguFXJmZl7eIMaEa+XiBqptDgS49OFy8m1bVtklYI7XNnhx5IxaP8A9F//xAAtEQACAgIBAwMEAQUBAQEAAAAAAQIRITESA0FRECJhBBMycYEgQpGhsWJgwf/aAAgBAgEBPwChFDKGXRfq14FIxYh2Q1kZnYsZszdM/u4r/A9vwJSdxavwxSUI29o5OVccIfG/yo5Ydv2/7RTUb7Yyh2mpJr9Dbkqen3I5vk7ONR70+5FNR8lY+RWkNNtCGmN/1PWhIob7HbLKtjSKFkTr0Teh+B7rT7MWc1lCV2p209MXP8e/Z+Rz5W1tfkjundxe13iRac6w2liRm2pfk+9HT4xhTz4vsSdP3HthrKYopW7wax2E6XwLOmVXcWyWy2hbH6a9KGL0bG7Ow2N0sEeTRmym3+im8rsKpxbVpijySt/pjlVV+Y3yinm9MlUX+PLOvA1T5LT35oVKW04tYfdo6bbdXjNElJ7pU8F8lxlXL/pl4dV5EsUWtNUjWEhKKRxzY7xQmJpvQ77ekv6WIeRRoqhIcmmbOMkb9FLjaSIWpd+L/wBHUqTqslx6sopxz3Wv8Fy5NqTxhxGlKXNcmv8ABVaeLwK5Jt0mtMV6brySSx7r+ThcrtWjjy1aHJdPGydumLDyNemxZRVPR/AkS/oyUMtWNWS0KNrY4NknSHNPppoi8pk3lXmyqnv+CMYtunSfzTFyS490sFxlbWGl/sjKMpqWmsSQ5OE8RVN/wxqljKl2s5KLVp4QmufL/Fi4yt0hZd1ke7qhLONFCrkU+47WhIb9FRoe/Siv6H6UhxUZFVY8rCyLkn8M41rY7msbT0ydtJqv/R9uLgk3+StNsiri1LlcNiacG448/PwLg5KcYt0/0q8MbcXx5XF1vsJOOOLps6qkp57kJLRV6qyNKXyTabpEEu7G1eGRyi7ZJ2L0oorJJUIaotiKIxsnFRQ8iT0V2byVJST7E4rku9nHD91vwYtXdk3Uk3FyfcnFxtv8f+EoRlClWEmqOtP7fUzcsbX/AO/KOpcUuKu0kku9DnKN3qSJRfPjFJ1p9j2q1nCJzeLL9yIqLuRxUs6M9ikxiVGLGi69LyU34RKlVGGiWzaGkl6JqxPiyXUTZhvbMJVY3GRHqSjJJp0L3yaxaMYd1JbJcpU0rT2yLbwvdxT5N9jg106T5vFJvaHFdV8KqUcw/S2hNucmop0Ql7qtxaumRlBbtp/9I1xTdY3EnNccPuPi5X/kWyCTVUKLTpEm0O79NlCTKsVlL0Sb2PBxQ949LIi/RJcR8Rq2JOXY990jTyvcSTkstZOj1OrDlB0dCC5TnnCy7/0R+1xU4QSkpWr2kdVylNTlFNp5SbvwdZyTW7ojzlyd06VnTz1ak7dP+Sd9NVe0SktEYpSeCMfdhYISVYJW3aG72K/RsXyJoadiKRViJfv0WGPJ2o1I5STHO3lDcdSE7z2OU+PHjgtbj3E7VSqzhGNRTdsnDp3XN86u0QjKHuTaxmO7Oh0odblcm5xVfuxx6ijGUllKpUTg31PbSSWL8Fdk8rSSG28SSTOeE4tuuzI+6TaWCk2K6Z0/kdrWiXyNISr0+DXYops16KWBu/XKOSaRNuLscsWkJpp2hKMo4oSayS6skraHPl1FSdMnDlLLeFao6U+XKNcfDHNPlad3iz6n6lxpQ5WfS9fqvq8tVfIh1l1pcYycY+JLfwffcJSh+Obr99ifVi3abs6anJcqv9jfsVEZOLeyImktifgawMuzZGLGx/5EsFV59Mr1vI3TIvkaHnDKlHF4Ipywlk+zOPYgpPp1T0T6XUglhfLOEkncbXkhDqtVtWdBNdN8llOs+CcHGXOTvwqon9P1ef3LSjWfLoj0FKNqEknun/sh9PPo/UwcupKT53TwfUfSOXUnJU+Ts6X0yUXp0z7FptI6nS9lRODU6UcnUj1ItOjp9Nzqlk+1KCurOS+3/AoTehpp5ZtljefS8CsdjWS7fosjt2JNMeWclxpiWKf8HQkuMl3sX3bf4sirjvNEOo+pyTp8Soy6LtaTPp4x4NLEWfTzlU080yPWcpSXi6wTm3OMbx3wJT300ne7HJqk4veLR9xdONytsUoPSWTrdefRt0qJda48kQTcXJly6rpLR0YuEc7H133TIrlH9nUn9uookn5EzZUTB3EmL0ba0ci+JtWNtMXclYm0iEZSXK8iSW5ZJJT6dxfZn0+pPHJEerHqJx002qOlFwbVN2dKUefUvElK61ZLpv7vNO3JYOpGXLnbutIXT5dNV1Gr70TlKPG53pEpJ8UyXTaScJHVTXSlyZ01z6aruT5dPqVb2dPpqDck9kJKSeR9NLeRVx9pS6yJRabVlNiXkoS9M1j0/lDaa9G7ObE3K7FSZz4t2RTmsM96dcqLk7t2c0qz7aE5xk8tRfgXUqeHt7JSlFtc5V5PuNxbvxQ7pS3a86ISpvfZPwOeHFPidfqynJPXjJ9PKclLk3rApdSMabyW9M+7xTimN3sTk1t0RfFYOUpbZcktkW49y25Z9GWxaNeiXf0vNejNjbWEY0x6qiMkqdk3m4iVvMqpEIpqUnUkRg3fFSG5OCpXWylSvuOPBLhVN5JSwqS3WCblFSVaqjpyk3wYumnJ9z6fbVEnf5WiUpSkvBdSrZHZxZlYENpx0YrI/wBMVsopDXq6QsrQ8sskxNIu2JNyyW6J4p1sQnUd2Jyg7SWdkurLpauhT5brLyJNr2vPaxqbjVfuiNa5RT7vJLjxptb2tnSbk5Vj24JPVK/NEG4tccE6aXnuSleUyMRJPsSlii7QnekNHwZoWGWLC9dFGX2ExtWOjFEbW9Du3RbG20qOeSM1yqSErk7lQ4xlO7ut/JBxcm+KteWRcJRqFrIk5K4OmtjabtrWbQkmnxrOmxKSXt7bKcEmsCTVO8D408UcV5x4IrisZRFUrbJtdhU1kTFffRTP5En3ZRX9KRyv0r5Ha2cmKXcUnHxTLprGCaz7VsTlVVobi1lZ7Mc02peEJU+XLAlbwlFihJ/rTF01G1eD3JrCivBXFtwjLl3KpqUo/wAeSMm6fYk3aquJGqzVdmKSWj3NEuMVYqaFgZQkxYZfohJDKwJN6E8jebHbY8bFKnRpWj9+nNKaqWCUpcuwmkqlC/kT6cfJiN/3H3HS9qspS92flEVGDdytdsEFybk2mRcv7k1X4lSUs202cFdWcVe8DzjwJIzQ6IpJid6obGJp+leix69xfDYnkzQhpMaSWiMrWhOV6Kt3dM4077Mm5qotYLv2uTQvc90RSut+Dh1Vbke5q1SXemUlF00/lkG003vycn323sT5P47idpKx0qTJcW95FFJYRxRhrQhOhfsee5G7L+RZ9EbN+lWNXQmxMbvvRmhNd8Cm3jR80Xaq/wCC5VsTklh2zlNxtpJoSvbLp0+5GS6j40v+CXTzTwNRrKfw7I1JpPwSq01IlxdN6Lbrsim8+DlWu4nJ7O2WMrArEvRPyJeiKMi+PROy4lpGx4aMMXGTWR+zumxtbMyyonJ9ljvQ1GstiSkkkkmu9ic3qWfjYpTl31uxuG+OxLCudoTi0lkUkm7SySdtt68WUsYwPlZvejFYYlyXpvYqQ+wqEkJIpCS0UVgVUYZ+zY0xV+ireSfJMtrsLg3m0Pkv/SMxWU6Yklp18i+5WypypHCKu3n4IvnUUsrsXxtWmZ3LF/7E6WFcSvd+NJ932G4vbsi3rSHLjkbxZdpCSSFXcWjb9H8iTRv0qykUhIafgu0KS02JqslodbPuW1atDaq1gi+WXRKllNo542xRfaSKxmSTOUpLdstRf4xci21VNZ7CklKmskUnfKWVo5SXwvgWcy0b/QpKVIecIbeBVQmmhCtsSEWIT9K8CQrawV8Ctf8Axv8A/8QAMBEAAgIBBAEEAQQABQUAAAAAAAECESEDEjFBUQQQImFxEzKBkSNCobHBBRRgYvH/2gAIAQMBAT8AQxi9ooSFFkYkV7KAkURSJYZyyLQ0uKGlVo6t/wBi+X5FtWVjyODk6TwKO21IzV1Y1lYd9eBPc6r+GYap/wBkfi7XPgaVpxRuV2uVyict0l0d82jDeRKolYI496YkJCiQWRIihRorIngTKRVDRwOqTE1Vibr6MLHKZdVKNJrlMw1u67IwrD46Y1hriS48Mbajy6fKFVJp4X2a0m52v5rshJONIVy5dNEpt8LIqk77Gtz7RVKmsFRb+mPCFVcFJ+yEhiQiMRogJFL2ihDpMw4nAsYMxkk+ByjHpvyjYpPN7SmpNcohclzXn7F8lT5Q8rjN8eCcEkpVnshtTwyUXF7o21/sVjd34LeJX+SML+SdlOXI27N/kjRRK0hSlXHtEooSIoiMgmi7KML2kWjhZOTa3TbJ/s5yjTbjm8FShCTTpeRSW1KucpltYdJiliqz2NRhKNZT6JNxpxjjoSk23VfXgc6W3NMfxfyyKD1Po0sIy44wbmz8nCLLVHPDGaa9qIoii0hO2JfEWCMhyNyI5FFqeSVVRBOnmhU4cEptJWraHUnfQ90UovKZKMowaeVymRipwzJ3/qiFPnEosSck0mkm8lPbtbw/BPfptW8Psa22rwLipUYcafPkUnZJuvoTiXaNzM0XgSvsRDgTEsFiKI4ZF4ExSNzkhO6FiQ0qLt54FUXnKZBpYt/Rve+64w0hvbNNbal0O9y3f/PsuWYuSVr858kUnckql/Vl7s2rSwaNbVVEoNRTJrhPiiaez6shDFsd1VfybZPmhpo44ENuTLaY2Pcnj2hybSIln2V0cEG2xItFp5SE4uLTIXt44N7xjHkzWDThujhpITi8L9xGbjO3fOTTg9TT+KS+mQSm/k3h5b6shpKTVLMX5IyioKUm1aSa7HvlUsU3mjSglxgUNy5NSLhUF/Y3KFx5RhPLLcUKybbK9mvBQzgimxKmRWCsiyxKjbgptENN0cHOaIqUSWnujaY/hG3wZprlPghGMcPDG15q2qRvTndbV5XkUnD5NtqWJfkpKMfk1eCWk6tU1jchw1W8JWv9id7mqbvKkaUG5/JNKskdyVddEV8Ua0839jlF5bwbVLyxYVMtEhyyXaF+B2UzbfLItIjlm5kOCKvgoapY9olsukOlQtu27H8l9EWo+cGrp6cts02a06jCOMvx/qT3uTjKTcap0aUUoOEXWOWsGhTXhWVGCSq07NVbdK4qk2s+BbdWVtcM04vk5SFOlTZqx8ipXdkbiuSVM+W1FSokkKzrkyKVCZVEDaVZpqh8o5RtjQoYwU+hRpG2O67EumbUqa4NzlbpURnNK9q23VMnNTW1pPOGa2tLRUfilCT/AKohPRc3CMll3HKzZB/4a3223mvJuxbjhq22ylGS27mhwzUltvtDuMUnyXSFL5I1cjdv8EJPotPPs26wPJEbNwzd9DQo0iPsuCqZDKEuin0S3RYpJqhaUZOkyOntg93JF1HFZ5s1IKKUrv6FFqkniuj0/pVJNyao/wCpaEVoKLfxdVi7aI+nlo02rku10iHov1NDT1H87jl/js/7aaVOKrt8moowajfI4/N7sm29vA1k2u+CSpZJSipZWSsWrNtCW1ckmNNZF/RJ12d2M/BtYhEYpoqjkiqRhm6MMtn6+nMltWrd4s0tXTm3TP1YNpKVMlPSi8unR6mSlqRUJYaFqKUNkcOs5NH1GktP9NW53jxknrq9rmm15X+how0NXQnsgv283bR6T1mnHQ09OeHCNOso9X6z5pW4pofrF8Yyaap8mjrN6qlN0si1FsTlJU+DRnpalpOzU1IaV7pUS9RGbrdSHb1v5Q9SClTdMg01yOlQoipIpDgikVZheRcHDEJ0kNix0bXdobPUJqUX1R/g0r3Jk2lPCxZPTjp7WryjK14/bR6lvfF9nqYRX6bXcbJaKUIyzmjS04rSlPvrJelLGo2q/bRoJObanWHdM0tD9ZuMVSxk9TGSnJSt7XX8Gl6fS16Scs+SHp/mompUZqHSohDS9Mtzlyeq1FqTtPA/TW1TJ3pzeeDRj+rJylmiDJRVc+zvgryYfvSfggxoSv2S9lSx0NRb4JzUXtpNEnu4jRD4aijJdo9VzFK6aHpS03GXKaTNaS1EnxRrQls0qzFxoU70tjVbWrNKS2fp4pt0+8oeqoamdNOurNDa97UKq2vo9JOozaxxZqa8NSb3QTRoJPXjt6ZrN6eq228Gk462nu2q6NXXlqxUWqo1YyhttcoevOVVgdudSw21Z8tCZptTgmJjf8jyNUYY0jFmBLJWBRyRikNJHK4P021gfw5Goyr42KMElUUhaVptxW6+SUYTirSbRsT06aTro2QpNQjfgUOFWOxYbVJU/HJJYWEuWvI9O5KTju8nptGEI4Vr8Gvsht2xSzlGotLUbaWO8dkVFZiqHpb6k4mnDbwSWmpftVk0p4YoacHcYqxxhN20r/BOKklaTIxSikl7vgYuB8e1t9IirEKrGqEkxJ9CWRxbdEY4SaLSwleSUmqXDJSUa3NUyG1ajvHgdu/ohc3U7tLB+m227eFefohFScWakIqG5EJ1FXg9Q7imuiMqarJGCSbNrcb8juhyjdnOUNJ/Qo/Iap+zYmZFlezbLLa8EVXtFFNiVClSKTZp87fBfTHmSwSUZR/BHSWpV8j06yrxwSfy+SxWaIbIy3f1ZLK3bZNdIhF704p8cMnFRUcf5sshC7z+LJxWbtijU3jmqZpx24f8F4obadN4NtvBlPo/JaTMPk45GWMZY2OTLS+/aKsQuSSTWBbWKuBRSY0Sg9txZaUVgTajSRqKUYq5On4NslJOecHEqkm0+DbKNK+cUyTcab66HsaW7umLbPF34+yU7e14dDc7XyshK+Vldk5bpZ5JO7VGmq/c2PmkOrpsbzRbobY5I3DZhjSaHTQ3Rf2bci9lToSTP0xwT/KFdEcYkOrwz5R4IppNeRy3LbWUWklbbRugkq5P1JSq1nngclVW2/JGe9JTa2s3tYUn+fBJKNqvkL5ebvwN8pX9oUdySY9ttEU26ModPLYq6LobxxkeTr2Y1IwYb8Hx7Kv2iKik1Ym0/Jh8HA4txyiEYNEk3TUuBqUx1Jr/ACs/TW7MsFyj8cV0xtzSpU+yTapJUSrmLWcSFJSh4pYHNuNpZL+ssXN+TI+Rq+B3JcDTSNv8C8DsTLHZbG3XGRKx0VYkNWyqFZGWasaKWGXg3Wq7RGMX8k8n/tSH8c1Y3avjyVpyraYTSdt9F5Vxprwyai00uClwlaS4H/h576FVuXkT3W1ghaTx/I226s33irFGW4uuxyRKTrg3ND4FJIwXZwjK6G27Gq6ot9M3NMocVQkhpITfQl2J0cNHxUuBpOWVRsjuw20P44SLxaXBW2NtvJNzdWld4Fu/ytfaL2RbIdpwwKLjdZ84F8c8/wDBdYfDOXkdJWhPLoSQ5Dyi4lZOB2OSN1cF15M2V4HdjWSNplWSVEShOSQvl0LODCw2OOFn8WRbTVJEm1Ldyn0SUYv9rp+RRjHFc+BRdbW7o4dRjTsppvh2OEqVN4I2klF5Pkrd57RHYy/HRbbyStPHHgTKSdkrLExlujPOB2K6tskfwX+ChYKTVkm0X3RBxaIpPslaVojTWcMxLtWJtc8roex5SyJwirFJ2nVryyoxt3SZSlTpopcRz/wONvLqQ5Oq3O10uyKkv2qiaUs8vwRi5LghF24srbL8DeR4JYHhUM/A/ss4HfRefLH/AAWJWcMrJGyUci8CguiNpj4Iu8NG03VVxZebSHGK6KtctLwftfKa+yrVxY28bVjsqLecv7OMJZQ345HHanK1YvjnyKna7Le6hksNE2q4LtZOzowNsvzklLJdl0+Tem+TevD/APDf/9k=";

// A widget that displays the picture taken by the user.
class DisplayPictureScreen extends StatelessWidget {
  final String imagePath;

  const DisplayPictureScreen({Key key, this.imagePath}) : super(key: key);

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Display the Picture')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              "Use this Picture?",
              style: GoogleFonts.cabin(
                color: Colors.black,
                fontWeight: FontWeight.w500,
                fontSize: 40,
              ),
            ),
            Image.file(
              File(imagePath),
              height: 400,
            ),
            CupertinoButton(
              onPressed: () {
                print("You clicked me");
                readFileAsString();
                Navigator.push(
                    context,
                    CupertinoPageRoute(
                        builder: (context) => TestScreen(imagePath: "test")));
              },
              padding: EdgeInsets.all(4.0),
              child: Container(
                  height: 100,
                  width: 350,
                  decoration: BoxDecoration(
                    color: Colors.lightBlue,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Container(
                    margin: EdgeInsets.fromLTRB(15, 0, 0, 0),
                    child: Align(
                      alignment: Alignment.centerLeft,
                      child: Text(
                        "Click here for First Aid advice",
                        style: GoogleFonts.bangers(
                          color: Colors.white,
                          fontWeight: FontWeight.w500,
                          fontSize: 30,
                        ),
                      ),
                    ),
                  )),
            ),
          ],
        ),
      ),
    );
  }
}

// A widget that displays the picture taken by the user.
class TestScreen extends StatelessWidget {
  final String imagePath;

  const TestScreen({Key key, this.imagePath}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    readFileAsString();
    return Scaffold(
      appBar: AppBar(title: Text('Results')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image(
              image: AssetImage('Datasets/DisplayImages/WaspBite.jpeg'),
              fit: BoxFit.cover,
            ),
            Padding(
              padding: EdgeInsets.fromLTRB(20, 20, 20, 40),
              child: Text(
                instructions,
                style: GoogleFonts.cabin(
                  fontSize: 20,
                  fontWeight: FontWeight.w400,
                ),
              ),
            ),
            CupertinoButton(
              onPressed: () async {
                final firstcamera = await getCamera();
                //print("Re-routed back to picture screen");
                Navigator.push(
                    context,
                    CupertinoPageRoute(
                        builder: (context) =>
                            TakePictureScreen(camera: firstcamera)));
              },
              child: Container(
                height: 35,
                width: 200,
                child: Align(
                  alignment: Alignment.center,
                  child: Text(
                    "Retake picture",
                    style: GoogleFonts.cabin(
                      fontWeight: FontWeight.w400,
                      fontSize: 30,
                    ),
                  ),
                ),
              ),
              color: Colors.lightBlue,
            ),

            Padding(padding: EdgeInsets.all(3.0)),
            CupertinoButton(
              onPressed: () async {
                final firstcamera = await getCamera();
                //print("Re-routed back to picture screen");
                Navigator.push(
                    context,
                    CupertinoPageRoute(builder: (context) => MyHomePage(title: 'AidFirst')));
              },
              child: Container(
                height: 35,
                width: 200,
                child: Align(
                  alignment: Alignment.center,
                  child: Text(
                    "Home Screen",
                    style: GoogleFonts.cabin(
                      fontWeight: FontWeight.w400,
                      fontSize: 30,
                    ),
                  ),
                ),
              ),
              color: Colors.lightBlue,
            ),
          ],
        ),
      ),
    );
  }
}

class FirstAidList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Select the Injury',
      home: Scaffold(
        appBar: AppBar(title: Text('Select the Injury')),
        body: ListBodyLayout(),
      ),
    );
  }
}

class ListBodyLayout extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return _injuryListView(context);
  }
}

Widget _injuryListView(BuildContext context) {
  final injuries = [
    'Ant Bite',
    'Bee Sting',
    'Wasp Bite',
    'First Degree Burn',
    'Second Degree Burn',
    'Third Degree Burn',
    'Mild Cut/Scrape',
    'Deep Cut',
    'Bruise',
    'CPR'
  ];

  Future<String> getFileData(String path) async {
    return await rootBundle.loadString(path);
  }

  Future readFileAsString(int index) async {
    final injuryFiles = [
      'AntBite',
      'BeeSting',
      'WaspBite',
      'FirstDegreeBurn',
      'SecondDegreeBurn',
      'ThirdDegreeBurn',
      'MildCut',
      'DeepCuts',
      'Bruise',
      'CPR'
    ];

    String fileName = injuryFiles[index];
    instructions = await getFileData('assets/' + fileName + '.txt');
  }

  String getDisplayImage(int index) {
    final injuryImages = [
      'AntBite.webp',
      'BeeStingArt.jpg',
      'WaspBite.jpeg',
      'FirstDegreeBurnArt.png',
      'SecondDegreeBurnArt.png',
      'ThirdDegreeBurnArt.png',
      'MildCutArt.jpg',
      'DeepCutArt.jpg',
      'BruiseArt.jpg',
      'CPR.webp'
    ];
    return injuryImages[index];
  }

  return ListView.builder(
      itemCount: injuries.length,
      itemBuilder: (context, index) {
        return CupertinoButton(
          padding: EdgeInsets.all(7.0),
          child: Container(
            height: 50,
            width: 375,
            decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(12),
                image: DecorationImage(
                  image: AssetImage("assets/ant.jpg"),
                  fit: BoxFit.cover,
                )),
            child: Container(
              child: Padding(
                padding: const EdgeInsets.only(
                  left: 15,
                ),
                child: Align(
                    alignment: Alignment.centerLeft,
                    child: Text(
                      injuries[index],
                      style: GoogleFonts.bangers(
                        fontSize: 30,
                        color: Colors.white,
                      ),
                    )),
              ),
            ),
          ),
          onPressed: () async {
            readFileAsString(index);
            int c = index;
            var b = context;
            String imageFile = getDisplayImage(index);
            Navigator.push(
                context,
                CupertinoPageRoute(
                  builder: (context) => TestScreen2(imagePath: imageFile),
                ));
          },
        );
      });
}

class TestScreen2 extends StatelessWidget {
  final String imagePath;

  const TestScreen2({Key key, this.imagePath}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Results')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image(
              image: AssetImage('Datasets/DisplayImages/' + imagePath),
              //'Datasets/DisplayImages/WaspBite.jpeg'),
              fit: BoxFit.cover,
            ),
            Padding(
              padding: EdgeInsets.fromLTRB(20, 20, 20, 20),
              child: Text(
                instructions,
                style: GoogleFonts.cabin(
                  fontSize: 20,
                  fontWeight: FontWeight.w400,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
